### ISSUE TITLE
Release 1.55

### ISSUE THREAD

**Issue by bearoso** [snes9xgit/snes9x#195] opened 2017-05-06 23:53 UTC
This will track existing issues blocking release of version 1.55.

I've updated the version number everywhere, and, as far as I can tell, the GTK+ port is stable.

Copyright notices still need updating.
changes.txt should be updated with changes from other ports.

**Comment by roflcopter777** [comment] 2017-05-07 00:12
1.55, eh? Looking forward to it :P

**Comment by OV2** [comment] 2017-05-08 18:39
I wanted to take a look at #180 and #187. The win port doesn't need any particular changes at the moment.
Maybe we should add the new BIOS_DIR as configurable to unix and gtk?
What was the state with #165 ? Either we have the black line, wrong display in at least one game or worse performance? Maybe I can try some more to get a correct solution without the branches.

**Comment by bearoso** [comment] 2017-05-09 01:30
For #165, the performance killer was the modulo, the branches were optimized away. I was trying a couple of things for it, but didn't get far. If you can get a fast, correct, version, I'm all for it. But if not, I think the slow, correct, version is the way forward.

Didn't realize there was a new BIOS_DIR. Will look into adding it.

**Comment by jristz** [comment] 2017-05-10 22:44
Actually in unix port I noticed that the compilling override my distro default fomr -02 to snes hardcoded -03, is there a possibility to fix it (since it also could affect llvm/clang building which have a -04) before releasing?

also someone should look the bugtracker and check duplicates and fixed and close them like #99 which is fixed with 1.54, or's like #164 is still happening?

finally, can someone give a date so I can check te translation a last time before the 1.55?
or check if the gtk3 port need some fixes?

**Comment by qwertymodo** [comment] 2017-05-17 21:26
Any chance of looking into #161 ?

**Comment by marcosfrm** [comment] 2017-05-19 16:22
@jristz I agree configure should not do that. I would follow this RPM Fusion patch...

https://pkgs.rpmfusion.org/cgit/nonfree/snes9x.git/tree/snes9x-1.54.1-unix_flags.patch

and let distros/users use their prefered compiler options.

(the LDFLAGS part is already done in https://github.com/snes9xgit/snes9x/commit/359b906b69f0443c02942fe6ac06513607cfeb7a)

**Comment by jristz** [comment] 2017-06-13 17:24
Reading more further in Gnome docs and mailist, GTK-2.22 is an LTS release, that mean is the target for GTK3 app and the gtk lts will be gtk-4.0 which is set to be released around 2 to 1.5 yeasr from now,
So targeting GTK-3.22 is supposed to be the desire and stable release... and not forgeting that even Debian 9 will have gtk 3.22 in they repos alongside all up to date distros I can check.

**Comment by wingedonezero** [comment] 2017-06-18 05:32
Can you look into #186 before release? Probably a easy fix since they work in windows. But a long time issue it seems since 1.53.

**Comment by OV2** [comment] 2017-07-01 19:10
I'll take a look at the libretro pr this weekend, but other than that I have no pressing issues I want to look into before a new release.
@qwertymodo could you verify that msu1 is working correctly in the latest version? It was broken until a few commits ago.

**Comment by qwertymodo** [comment] 2017-07-01 19:35
I just tried the latest release and something really weird is broken in MSU-1.  The first track that loads, it's like it plays for a split second and then jumps forward about a second or two into the track.  I suspect b3b38a6d1adebeed870b093448643e8298588411 is the culprit, because removing that line removes all of register initialization on power-up.  I'm testing now to confirm.

**Comment by OV2** [comment] 2017-07-01 20:29
S9xMSU1Init is called in S9xReset and S9xSoftReset, and both functions call S9xResetMSU before, that's why I removed it.

**Comment by qwertymodo** [comment] 2017-07-01 20:32
Yes, I can see that now.  I'm attempting a bisect to track down the actual issue, but it's slow going because so much has changed in terms of build config and dependency removals.  I have, however, confirmed that the issue does NOT exist in 2db1653836ef5baae724979bb04d80bf60919433 which doesn't really help much other than to confirm that 1) I'm not crazy and 2) it's not an issue with my system.  I'll update if I figure out anything further, but until this is fixed, I'd consider this a release blocker (it's not just the one audio skip, it seems to happen on a lot of tracks, but I can't figure out a pattern other than definitely on the first track).

**Comment by OV2** [comment] 2017-07-01 21:13
I only have the chrono trigger rom to test with, and that works fine for me (both audio and video). I missed pushing one commit, but that fix shouldn't have any effect on msu...

**Comment by qwertymodo** [comment] 2017-07-02 03:18
Ok, I've tracked down the problem.  6b46ed0d00c5b94b7f19b8353510ae8061b5e9f0 works fine.  cf846e0c56962f724c5f84c10b926de8884b8f95 is the one that completely breaks MSU-1 resulting in silence, but if you apply just 0df033d3b749d6e121807e1d1a72f85d617c6128 to fix the silence, the stutter occurs.  So it sounds like there are further problems with cf846e0c56962f724c5f84c10b926de8884b8f95.  Possibly another missing double cast, or possibly we've missed a 32040 somewhere.

**Comment by qwertymodo** [comment] 2017-09-07 20:21
The windows rc file needs the version number updated.

**Comment by jristz** [comment] 2017-09-27 07:12
I was loking and look like this https://github.com/megari/snes9x/commit/5d6a7199bb2e2342b7276d579ed1da2a9f9c3ee1 fix some of the deprecation on gtk, not sure if is enough to re-enable or plain move to gtk3 now.

**Comment by OV2** [comment] 2017-10-01 13:36
Should we give this another go? I've updated changes.txt with win32 changes and the other changes I could see / remember.

@bearoso I just remembered that I sent you a PM on the s9x forums a while ago regarding the git repo / organization, could you take a look?

**Comment by bearoso** [comment] 2017-10-03 20:27
I'm fine with doing the organization thing you mentioned in the Snes9x forums.

We could also add the temporary timing hack to fix Chou Aniki from bug #187.

Copyrights need to be updated. @qwertymodo How do you want to be referenced in the copyright block?

**Comment by qwertymodo** [comment] 2017-10-03 20:50
qwertymodo works for copyright references.

**Comment by bearoso** [comment] 2017-11-17 22:05
Updated the copyright notices. Should we add the timing hack for #187?

**Comment by OV2** [comment] 2017-11-19 17:55
Yes, I'd add that.

Maybe @tmkk wants to provide a macos binary if we do a release?

**Comment by bearoso** [comment] 2017-11-19 18:22
Are there any other blockers?

**Comment by OV2** [comment] 2017-11-19 18:59
Not that I know of. I never managed to reproduce the msu1 fast-forward desyncs quertymodo reported, so I'd just release it and see.

**Comment by roflcopter777** [comment] 2017-11-19 19:07
Ooh, is 1.55 ready for release? Nice.

**Comment by bearoso** [comment] 2017-11-19 22:12
Ok, I've uploaded the source tarball to sites.google.com/site/bearoso
I'll upload the win binaries when you make them.

**Comment by jristz** [comment] 2017-11-19 22:46
Does the GTK3 build is ready with this new version soon to be release?

**Comment by qwertymodo** [comment] 2017-11-19 23:02
> I never managed to reproduce the msu1 fast-forward desyncs quertymodo reported

Minor FYI, it's qw not qu, I've seen it spelled incorrectly in some parts, including changelogs on s9x-w32.com, I hope it's correct in any official releases (I believe is correct in all of the copyright headers).

**Comment by bearoso** [comment] 2017-11-19 23:48
@jristz I wanted to get this release out before doing any major changes. I'm looking at bumping to GTK3, SDL 2.0 afterwards.

**Comment by qwertymodo** [comment] 2017-11-19 23:52
I just got a weird memory mapping bug report from Conn that I'd like to look into tonight. I'm traveling at the moment, but should be able to look into in in about 6 hours or so.

**Comment by OV2** [comment] 2017-11-20 00:04
I've just uploaded the [binaries](http://s9x-w32.de/dl/) and mirrored the source tarball.

q**w**ertymodo: take your time - if it is a serious issue we'll do a .1 like last time. Sorry about the misspelling, I don't know why I always go to the u instead of following the keys ;) Will make sure to fix it in future mini-changelogs.

**Comment by qwertymodo** [comment] 2017-11-20 00:06
Ok, that works. So does this mean v1.55 is officially released? :) Can you post the links?

**Comment by roflcopter777** [comment] 2017-11-20 02:07
I think they have to be compiled, no?

**Comment by tmkk** [comment] 2017-11-20 03:54
@OV2
This is a Mac build for intel machines.
[snes9x-1.55-macosx-i386.zip](https://github.com/snes9xgit/snes9x/files/1486394/snes9x-1.55-macosx-i386.zip)

**Comment by OV2** [comment] 2017-11-20 11:26
Thanks tmkk, uploaded it to the other binaries.

qwertymodo: I posted the link above: http://s9x-w32.de/dl/

**Comment by qwertymodo** [comment] 2017-11-20 14:49
Thanks, I just missed the link the first time around.  It was a little hard to see on my phone.

**Comment by qwertymodo** [comment] 2017-11-20 14:54
I see @bearoso already tagged 1.55 in the repo, so I went ahead and turned the tag into a release here: https://github.com/snes9xgit/snes9x/releases/tag/1.55

**Comment by qwertymodo** [comment] 2017-11-20 19:37
I've followed up with Conn, and the bug was in the asm, not the emulator.  So that's a non-issue.

**Comment by GB-CG** [comment] 2017-11-20 21:26
It's nice to see it getting an Mac update, but It still reads 1.53 on the outside of the Mac app though.
<img width="275" alt="screen shot 2017-11-20 at 9 13 55 pm" src="https://user-images.githubusercontent.com/11931125/33041954-08f3a05a-ce38-11e7-976a-338199840a16.png">

**Comment by jristz** [comment] 2017-11-21 00:11
So now with the 1.55 released technically we could close this bug and open the new found bugs (like the one GB-CG mention) in they respective bugs pointing to the next release...

**Comment by qwertymodo** [comment] 2018-01-05 20:52
Closing this.  If we need to put out a point release like we did for 1.54.1 we can open a new meta issue for that, and bug reports should be filed separately.

**Comment by qwertymodo** [comment] 2018-01-05 20:53
Closing this.  If we need to put out a point release like we did for 1.54.1 we can open a new meta issue for that, and bug reports should be filed separately.

**Closed by qwertymodo** 2018-01-05 20:53 UTC
Labels: meta
