### ISSUE TITLE
Kick off is full of Garbage.

### ISSUE THREAD

**Issue by ghost** [snes9xgit/snes9x#250] opened 2017-10-12 16:54 UTC
![2017-10-12](https://user-images.githubusercontent.com/30609937/31508540-ca3a97e4-af54-11e7-84b9-a6f39acf1bb0.png)

This happens with both european and japanese versions.

Tested in the latest test build.

**Comment by jjfmz42015** [comment] 2017-10-12 18:50
same result here with every SNES9X build I tried. 1.53 to latest.

Rom checksum is good and works proper in bsnes classic.

**Comment by jjfmz42015** [comment] 2017-10-12 23:02
ok tried this on zsnes 1.51, bsnes, snes gt its fine. then tried on snes9x 1.53 to latest build broken.

just reporting to try and help.

**Comment by bearoso** [comment] 2018-05-17 21:30
It writes to vram outside of vblank. Disabling that check fixes the graphics there.

**Comment by jjfmz42015** [comment] 2018-05-18 14:30
do you mean disabling in the interface? I can not find that

**Comment by OV2** [comment] 2018-05-18 14:34
There is an option in the .conf file "BlockInvalidVRAMAccess"

**Comment by jjfmz42015** [comment] 2018-05-18 14:40
this worked.
Does changing this from true to false cause other issues?

**Comment by OV2** [comment] 2018-05-18 14:43
Yes, there are some games that need this blocked (Hook for example).

**Comment by jjfmz42015** [comment] 2018-05-18 14:47
hmm, so can this be added as a option in the menus? or maybe have a routine in snes9x that disables it specifically for games that need it disabled? based on rom checksum?

**Comment by bearoso** [comment] 2018-05-18 15:01
Nothing really *needs* this. It's just that bugs in Snes9x or timing problems cause games that write to vram only during vblank normally to write outside that period on Snes9x. It's true by default to let ROM hackers know that it's not normal to write to vram whenever; it would break on a real SNES.

**Comment by jjfmz42015** [comment] 2018-05-18 15:10
It does break Hook. Just tested.

set to true hook is broken
set to false kick off is broken

not a big deal just like testing

**Comment by kps501** [comment] 2018-05-22 00:39
Kick Off (Europe) menu now fixed as of 2018-05-21! 2018-05-15 was still broken.

**Comment by jjfmz42015** [comment] 2018-05-22 03:06
Hmm i wonder if they just reversed the vram setting breaking hook or if they made it detect the rom then disable?

**Comment by kps501** [comment] 2018-05-22 11:45
You're right! - checked memmap.cpp and Kick Off is there. Changed rom header and vram garbage kicks in again. Still nice not seeing that bug though, even as workaround.

**Comment by kps501** [comment] 2018-05-22 17:32
Worked with someone and found the cause!

ppu.h
static inline void REGISTER_2118 (uint8 Byte)
{
CHECK_INBLANK();

When inblank fails, it's supposed to bump vram ptr but doesn't happen.

**Comment by jjfmz42015** [comment] 2018-05-22 17:52
I was just curious what they did in the latest build. they identified your finding themselves earlier.

**Comment by bearoso** [comment] 2018-05-22 17:56
No, we just allowed invalid vram access for this game. I’ll see if this is the problem in a little bit.

**Comment by bearoso** [comment] 2018-05-22 19:56
That does the trick. Fixed and removed hacks.

**Closed by bearoso** 2018-05-22 19:56 UTC
