### ISSUE TITLE
The SA1 chip emulation has no synchronization or relative timing

### ISSUE THREAD

**Issue by ghost** [snes9xgit/snes9x#71] opened 2015-04-21 02:33 UTC
During the intro, there is some slowdown that does not occur on real hardware, which causes the music to finish playing before the end of the intro.  This issue alsodoes not appear in emulators such as bSNES.

**Comment by andoruB** [comment] 2015-05-10 15:30
IIRC this also happened in zsnes 1.51 (and I think most of the latest versions)

**Comment by jfields687** [comment] 2015-06-03 17:02
I can confirm this happens in zsnes 1.51 as well. The only emulator that it works correctly in is higan. Seems to be something with mode 7 rotation?

**Comment by vgturtle127** [comment] 2015-09-27 05:52
We need to try the latest version of snes9x, zsnes, and higan. This may not even be an issue anymore...

**Comment by jfields687** [comment] 2015-09-27 13:46
Snes9x: Does not work
Zsnes: Does not work
Bsnes/Higan: Works correctly

**Comment by vgturtle127** [comment] 2015-09-28 04:36
Did you try the latest test build of SNES9X?

ZSNES is getting a new build sometime this year, apparently they have converted much of the code from Assembly to C. That should be interesting.

Higan runs everything perfectly, but I can never seem to get it to run on any of my systems... :disappointed: 

I need to get the game and do some testing. Let me see if I can find the game. I may have it in storage somewhere.

**Comment by vgturtle127** [comment] 2015-09-28 17:18
Alright, I found my copy and I dumped the ROM (well, ROM's plural).

I tried the NTSC-U version, the PAL version, and both NTSC-J versions.

Performance never changed for me in the intro, and I used the following settings:

I used the default settings for Input, Sound, and Emulation.

I used the following display settings:

Direct3D output
Fullscreen and Emulated Fullscreen unchecked
Stretch Image and Maintain Aspect Ratio checked (4:3 for the Aspect Ratio)
Show Frame Rate checked
Bilinear Filtering and Vsync unchecked
Automatic Frame Skipping on, with Max Skipped Frames set to 0
2xBRZ filter on for both low and high res
Fullscreen settings set to native resolution of my display (1440 x 900), with 32-bit and 60Hz selected
Triple Buffering enabled
Transparency Effects, Hi Resolution Support, and Blend Hi-Res Images checked
Extend height of SNES Image and Display messages before applying filters unchecked

When I tested them, I let the intro run until it was at the main menu. Then I restarted SNES9X and loaded the next game (just in case).

The NTSC-U and NTSC-J versions run at 60Hz (AKA 60FPS), and the PAL version runs at 50Hz (AKA 50FPS).

The intro did slow down when I just ran the game at first, but I had 4xBRZ on. When I switched it to 2xBRZ, it ran fine.

If you guys want me to run any extra tests I would be happy to, just tell me how you want me to run the test and I will do it. :smile:

**Comment by Awakened0** [comment] 2017-10-24 03:22
I noticed this bug when comparing SNES9x libretro to higan libretro.

**Comment by VitorVilela7** [comment] 2017-11-20 20:09
This issue occurs because Snes9x runs SA-1 underclocked at around ~7.21 MHz instead of ~10.74 MHz. You can see more information about it here: http://www.snes9x.com/phpbb3/viewtopic.php?f=6&t=17276

There's a few easy fixes that can be done to improve the SA-1 clock slightly, but it's likely that the main problem is the clock divider (or multiplier, if it's based from the 2.68 MHz clock) between the SNES CPU and SA-1 CPU emulation cores:
 - Remove WRAM refreshes on SA-1 side (SA-1 doesn't have access to WRAM).
 - Don't lock SA-1 CPU while SNES DMA or H-DMA is running (they have nothing to do with the CPU, even if DMAing from ROM).

**Comment by bearoso** [comment] 2017-11-20 20:25
The way the SA1 is implemented with #ifdefs recycling the CPU code makes working with it very painful. It might be difficult to fix this without some heavy restructuring.

**Comment by bearoso** [comment] 2017-11-20 22:11
The SA1 timing in Snes9x is deterministic, but completely arbitrary. Actually using the correct speed ratio doesn't seem to be a concern for the original implementers.

**Comment by bearoso** [comment] 2017-11-20 22:56
Yeah, there's no timing for the SA1. Add an extra call to S9xSA1MainLoop to cpuexec.cpp in the same place the old one is and it effectively double-clocks the SA1 and fixes Kirby's speed.

**Comment by VitorVilela7** [comment] 2017-11-21 01:41
Yeah, so that's it. Probably it's likely that there's no easy fix for this without rewriting a good part of the core. So I suppose after doing that hack, the internal speed jumped to around 14.60 MHz. You could test it with https://www.dropbox.com/s/v65la9avytgh23s/speed_test.sfc?dl=1 (source available at https://www.dropbox.com/s/k11e016irais9po/src.zip?dl=1 )

Unsure but, if there's no real plans in the rewriting the CPU core for now probably it might be better to leave that hack with, haha? I suppose more games could work better with it, such as SMRPG (which has also some noticeable lag in its intro in Snes9x as well) and even my ROM hack (which I use SA-1 but I can't force it more otherwise it would only run smoothly in bsnes or real hardware). Might be good to test how the other games behave with it (there's no that many fortunately).

Still, a rewrite would be a better thing to do.

**Comment by bearoso** [comment] 2017-11-21 02:25
Actually, it shouldn't be too difficult to get close to correct timing. The code counts instruction clocks properly, as it's based on the SCPU, so we should just need to add relative clock scaling. The SuperFX is much worse off.

**Comment by bearoso** [comment] 2017-11-22 00:15
I committed a fix that gets the measured speed to ~12mhz.

What the core is doing is for every CPU opcode executed, it executes 3 SA1 opcodes, probably based on the thinking that it would be close to correct because the CPUs are similar and the SA1 is 3 times as fast. 

The problem is, as you mentioned, the S-CPU is doing all sorts of stuff that consumes CPU time that isn't just reading and executing instructions, like WRAM refresh, DMA, so the original author's estimate isn't very good.

I've tried messing with counting cycles for parity, but something in their implementation is incomplete, and I can't find out where because, as I said, the SA1 is mostly a macroed over, convoluted version of the S-CPU.

My tweak gets behavior closer to the console. It's certainly not correct, but since it's less incorrect we'll go with it until there's a better solution.

**Comment by VitorVilela7** [comment] 2017-11-22 02:44
The correct ratio would be four S-CPU cycles for every SA-1 opcode (8 master cycles vs. 2 master cycles). I suppose since some operations by S-CPU are done in six master cycles, it might explain the actual 3:1 ratio (3.58 MHz x 3 = 10.74 MHz in theory). But yeah, probably the better approach would be e.g.. making it master cycle accurate to account everything properly but while there's no better solution yet, ~12 mhz is a much better speed compared to ~7 mhz.

Too bad we only found out about this after the 1.55 release, but hey, still it's a pretty good change which I was been wanting to it happen since 2014 or so! Thank you for far for the workaround!

**Comment by bearoso** [comment] 2019-03-09 23:56
I think we're pretty close now, without further increasing CPU usage.

**Closed by bearoso** 2019-03-09 23:56 UTC
Labels: bug, emulation-ppu
