### ISSUE TITLE
Game Boy Games Support PLS

### ISSUE THREAD

**Issue by CraftFan22** [snes9xgit/snes9x#759] opened 2022-04-11 11:42 UTC
Please Add Support For Game Boy Games **(with .gb & .gbc File Extension)**. Add **SGB ROM BIOS** In **System Options** To Game Boy Games Require A **Super Game Boy or Super Game Boy 2 (.sfc File Extension)**. When If You Play Game Boy Games On **SNES**, It Will Show A **Super Game Boy Borders**. The Super Game Boy Menu Is **L+R**.

**Comment by bearoso** [comment] 2022-04-11 15:26
Duplicate of #758.

**Closed by bearoso** 2022-04-11 15:26 UTC

**Comment by CraftFan22** [comment] 2022-04-11 16:20
**Watch How To Emulate Super Game Boy On SNES Emulator** https://youtu.be/Z_vgTpDKK3Y
