### ISSUE TITLE
Super Robot Taisen Gaiden - Masou Kishin - The Lord of Elemental crashes Snes9x

### ISSUE THREAD

**Issue by ImSpecial** [snes9xgit/snes9x#316] opened 2018-05-30 15:19 UTC
Super Robot Taisen Gaiden - Masou Kishin - The Lord of Elemental (Japan)
Snes9x 1.55 (OV's test build 05-24-2018)
Windows 10 64-bit

During the intro sequence before the first mission the emulator just locks up.

Not sure what else to add. :/

**Comment by OV2** [comment] 2018-05-30 16:19
Seems to no longer be an issue in the latest git.

**Comment by ImSpecial** [comment] 2018-05-30 16:30
Just grabbed the latest off of [EmuCR](https://www.emucr.com/2018/05/snes9x-git-20180530.html) and it still happens.

https://i.imgur.com/VBqj6j8.png

And with a clean Snes9x.ini

https://i.imgur.com/pTGGYtI.png

**Comment by OV2** [comment] 2018-05-30 16:55
You can try the most recent automatic appveyor build: https://ci.appveyor.com/project/snes9x/snes9x

I'll make a new testbuild soon.

**Comment by ImSpecial** [comment] 2018-05-30 17:13
Yeah same thing unfortunately.

https://i.imgur.com/2PbaEAx.png

**Comment by bearoso** [comment] 2018-05-30 17:38
I'm using the same rom image and it works. On GTK+ port, at least.

**Comment by ImSpecial** [comment] 2018-05-30 18:01
For what its worth, I wasn't able to get it to crash with higan_v106-windows

**Comment by OV2** [comment] 2018-05-30 18:28
I can't even get it to crash with the emucr build. How are you triggering it? Are you just pressing A until you get there? Do you let it idle somewhere?

**Comment by bearoso** [comment] 2018-05-30 18:33
I'm not even getting a crash with the new translation patch.

**Comment by bearoso** [comment] 2018-05-30 18:43
I notice in his screenshots that the whole program is unresponsive. Maybe something to do with syncing spinlocking again?

@ImSpecial: Try turning off sound syncing and/or the automatic input rate box and see if it still locks up.

**Comment by ImSpecial** [comment] 2018-05-30 18:43
I should say that it happens "sometimes". I have gotten past this part before, but the crash seems to happen very regularly, it might be turbo related? Like, as I'm testing and reproducing this over and over again, I just hold down the turbo key to get to this part. I can make a Save state right before, and sometimes get past it, sometimes it locks, it's like a 50/50.

All I can say is maybe try several times.

**Comment by ImSpecial** [comment] 2018-05-30 18:45
I've tried with both ound syncing on/off with no difference, Not sure what " automatic input rate " is...

**Comment by bearoso** [comment] 2018-05-30 19:00
No cheats enabled, either?

**Comment by ImSpecial** [comment] 2018-05-30 19:01
Nope, happens with a clean snes.conf file too, also I'm [not alone](https://www.romhacking.net/forum/index.php?topic=26422.msg359882#msg359882) so it's nice knowing I'm not crazy here.

**Comment by bearoso** [comment] 2018-05-30 19:15
Ok, I reproduced it on windows using a release build, but couldn't on a debug build. That's not good, because it might be the optimizer screwing with things.

**Comment by jjfmz42015** [comment] 2018-05-30 20:12
Just tried it on Snes9x 1.55-171 Dev Build May 30 2018  appveyor no crash

**Comment by bearoso** [comment] 2018-05-30 20:17
I've already reproduced the crash numerous times. It's temperamental and dependent on compiler. I'm trying to track it down.

**Comment by jjfmz42015** [comment] 2018-05-30 20:20
i see that you have im saying these two builds dont so maybe that helps i dunno :)

**Comment by bearoso** [comment] 2018-05-30 20:31
I've tried that build, too. It still crashes. It's random: if you can run through it 5 times or more with no crashes, then it's probably ok.

**Comment by bearoso** [comment] 2018-05-30 20:54
Tracked it down to 355365046904b679d33b52c197ff423057ba6172, the Speedy Gonzales commit. For some bizarre reason, this coupled with enabling optimization causes the crash. Only on Visual Studio. With gcc and clang on Linux it's fine.

**Comment by OV2** [comment] 2018-05-30 21:04
I've tried the latest git about 20 times and only got the crash once, so I guess it's somehow timing related?

**Comment by bearoso** [comment] 2018-05-30 21:06
I was guessing more like uninitialized memory being used. But I don't know why that commit would cause it.

**Comment by bearoso** [comment] 2018-05-30 21:06
But the uninitialized memory thing does fit with the debug/release discrepancy.

**Comment by bearoso** [comment] 2018-05-30 22:04
Should be fixed now. No idea why the VS optimization broke it. I moved the openbus set to the last register Speedy writes during HDMA, 212D, since we know that because Speedy does it that the hardware does it, too. It's very likely that having all PPU writes go through OpenBus was wrong, so this is a better fix.

**Closed by bearoso** 2018-05-30 22:04 UTC

**Comment by ImSpecial** [comment] 2018-05-30 22:42
Using the latest appveyor build, I gave the intro probably a good 10 run-throughs and was not able to get it to lockup once, so I'm thinking you got this bug fixed.

**Comment by bearoso** [comment] 2018-05-30 22:48
One can only hope so. :-)

**Comment by OV2** [comment] 2018-05-31 10:57
I think I've found the root issue in S9xGetWord:
`return (OpenBus | (S9xGetByte(a.xPBPC) << 8));`

Bitwise or does not specify an evaluation order, and MSVC will reorder it to this:
```
00000001400612CE  mov         ecx,dword ptr [a]  
00000001400612D2  call        S9xGetByte (0140060BE0h)  
00000001400612D7  movzx       ecx,al  
00000001400612DA  movzx       eax,byte ptr [OpenBus (01405AEED3h)]  
00000001400612E1  shl         ecx,8  
00000001400612E4  or          ax,cx  
```

This causes problems when OpenBus changes during S9xGetByte, in this instance when HDMA triggers and S9xSetPPU runs. Looks like this:
```
$00:91C3 7C E1 9F    JMP ($9FE1,x)[$00:9FB0] A:001E X:001E Y:0000 D:0000 DB:01 S:0374 P:envmxdizc HC:1068 VC:163 FC:56   V .    HT:10 VT:223 C:81850
*** HDMA Transfer HC:1108, Channel:60
--- HDMA PPU 2132 -> 80
--- HDMA PPU 2132 -> 40
--- HDMA PPU 2132 -> 20
$00:9F20 1F 00 49 1F ORA $1F4900,x[$1F:491E] A:001E X:001E Y:0000 D:0000 DB:01 S:0374 P:envmxdizc HC:1166 VC:163 FC:56   V .    HT:10 VT:223 C:81850
$00:9F24 00 1A       BRK #$1A                A:1F1F X:001E Y:0000 D:0000 DB:01 S:0374 P:envmxdizc HC:1210 VC:163 FC:56   V .    HT:10 VT:223 C:81850
*** BRK
$00:E875 78          SEI                     A:1F1F X:001E Y:0000 D:0000 DB:01 S:0370 P:envmxdIzc HC:1274 VC:163 FC:56   V .    HT:10 VT:223 C:81850
$00:E876 DB          STP                     A:1F1F X:001E Y:0000 D:0000 DB:01 S:0370 P:envmxdIzc HC:1288 VC:163 FC:56   V .    HT:10 VT:223 C:81850
```
(address discrepancy between the disassembly of JMP and the next command)

The lockup is then because it runs into an STP command, in which case we no longer leave the main loop unless we're in DEBUGGER mode. Should we maybe add DEBUG_MODE_FLAG as a break condition even in regular mode?

**Comment by bearoso** [comment] 2018-05-31 16:06
> Should we maybe add DEBUG_MODE_FLAG as a break condition even in regular mode?
Probably. I don't imagine a state where we never return from S9xMainLoop is ever a good idea.
