### ISSUE TITLE
Snes9x Git (2018/05/23) crashes with every game

### ISSUE THREAD

**Issue by Cibomatto2002** [snes9xgit/snes9x#305] opened 2018-05-23 16:46 UTC
Just got the Snes9x Git (2018/05/23) test build and both x86 and x64 crashes on any game. just load any game and you get this screen. Snes9x Git (2018/05/21) works correct.

![capture5-23-2018-11 46 28 am](https://user-images.githubusercontent.com/21169038/40438906-f87c0f0a-5e7e-11e8-90bd-353ebe52f696.jpg)

**Comment by bearoso** [comment] 2018-05-23 16:49
Duplicate of #304

**Comment by jjfmz42015** [comment] 2018-05-23 17:20
not true.

if select ogl disable extended height and choose 2xsal will happen on ALL windows builds from 1.54 up all appveyor builds all test builds

**Comment by bearoso** [comment] 2018-05-23 17:22
Sorry, assumed they were the same.

**Comment by jjfmz42015** [comment] 2018-05-23 17:48
dont be sorry im just trying to help.

ive now noticed on builds before OGL was altered this does not happen.

**Comment by Cibomatto2002** [comment] 2018-05-23 22:31
I made a video on how I get it to crash. https://www.youtube.com/watch?v=4eApfumtS14&feature=youtu.be

**Comment by bearoso** [comment] 2018-05-23 22:32
I already know why it's crashing. I was waiting for OV2 to do it, but I'll fix it.

**Comment by OV2** [comment] 2018-05-23 22:44
I gave it a quick look but didn't have the time to properly make a fix yet. Some of the filters need to correctly use the height returned form SetRect.

**Comment by bearoso** [comment] 2018-05-23 22:46
Also, at the top of S9xDeinitUpdate, the logic is wrong and sets the height to 239, which is and isn't used.

**Comment by OV2** [comment] 2018-05-23 22:54
That should be fine, it always forces extended height there and then removes it depending on the GUI setting.

**Comment by bearoso** [comment] 2018-05-23 23:00
Well, just for your info, that's how I fixed it. Changed the top part to:
```
	if (GUI.HeightExtend)
	{
		if (Height == SNES_HEIGHT)
			Src.Height = SNES_HEIGHT_EXTENDED;
		else if (Height == SNES_HEIGHT * 2)
			Src.Height = SNES_HEIGHT_EXTENDED * 2;
	}
	else
	{
		if (Height == SNES_HEIGHT_EXTENDED)
			Src.Height = SNES_HEIGHT;
		else if (Height == SNES_HEIGHT_EXTENDED * 2)
			Src.Height = SNES_HEIGHT * 2;
	}
```
Because the filters and the message string drawing were using Src.Height of 239 and doubling it to 478 and overflowing the output buffer that was tightly sized for the expected 224 height.

**Comment by bearoso** [comment] 2018-05-23 23:53
Here's my alternate solution that doesn't require much reworking. Expand the buffer if it's a non-extended height multiple:
```	if(!drawTexture) {
		unsigned int bufferHeight = height % SNES_HEIGHT == 0 ? height * 239 / 224 : height;
		outTextureWidth = width;
		outTextureHeight = height;

		glGenTextures(1,&drawTexture);
		glBindTexture(GL_TEXTURE_2D,drawTexture);
		glTexImage2D(GL_TEXTURE_2D,0,GL_RGB, outTextureWidth, outTextureHeight,0,GL_RGB,GL_UNSIGNED_SHORT_5_6_5,NULL);
		if(pboFunctionsLoaded) {
			glGenBuffers(1,&drawBuffer);
			glBindBuffer(GL_PIXEL_UNPACK_BUFFER,drawBuffer);
			glBufferData(GL_PIXEL_UNPACK_BUFFER, outTextureWidth*bufferHeight * 2,NULL,GL_STREAM_DRAW);
			glBindBuffer(GL_PIXEL_UNPACK_BUFFER,0);
		} else {
			noPboBuffer = new BYTE[outTextureWidth*bufferHeight * 2];
		}

		glTexParameteri (GL_TEXTURE_2D, GL_TEXTURE_WRAP_S, GL_CLAMP_TO_BORDER);
		glTexParameteri (GL_TEXTURE_2D, GL_TEXTURE_WRAP_T, GL_CLAMP_TO_BORDER);
	}

**Comment by OV2** [comment] 2018-05-24 00:08
That's probably the easiest fix - I'll still try to untangle the height issues inside the software filters tomorrow.

**Closed** 2018-05-24 13:54 UTC

**Comment by jjfmz42015** [comment] 2018-05-24 15:18
latest appveyor with this fix failed
