### ISSUE TITLE
Chinese name ROM is not supported

### ISSUE THREAD

**Issue by shooterspps** [snes9xgit/snes9x#826] opened 2023-03-12 03:50 UTC
After the 1096 nightly version, the Chinese name rom is not supported, and the loading directly crashes

**Comment by OV2** [comment] 2023-03-12 14:01
I wasn't able to reproduce this - do you have a sample rom name?

**Comment by kingboxnt** [comment] 2023-03-12 14:09
e.g: 梦幻模拟战2.smc

**Comment by OV2** [comment] 2023-03-12 14:26
A rom named like this works fine on my system. Does it work if you rename it to something else?

**Comment by kingboxnt** [comment] 2023-03-12 14:37
After renaming, it still crashes. Version 1096 can run
Windows 10
Simplified Chinese operating system

**Comment by bearoso** [comment] 2023-03-12 16:36
I probably overlooked something with the std::strings and the utf8/16 conversion somewhere.

**Comment by OV2** [comment] 2023-03-12 16:43
@kingboxnt: can you provide a sample rom somewhere? I wasn't able to find it in a cursory search.

**Comment by bearoso** [comment] 2023-03-12 16:50
@OV2: I think it's probably Der Langrisser. 

@kingboxnt, are you using a translation patch with it?

**Comment by OV2** [comment] 2023-03-12 17:01
I found a chinese version of der langrisser, but that still worked. Maybe I can try it on monday with a windows set to simplified chinese.

**Comment by kingboxnt** [comment] 2023-03-12 17:34
only the file name, english or japanese rom to change the chinese name also can not, should be the above-mentioned utf8/16 problem

**Comment by bearoso** [comment] 2023-03-12 22:39
@kingboxnt. You're on Windows 10, but do you know which update pack you're using? Like 2H22 or something. There was an update at some point in 2019 where Windows 10 changed its ASCII functions to be full UTF-8, and I'm wondering if we're not seeing the bug because we only have later versions of Windows.

**Comment by kingboxnt** [comment] 2023-03-13 01:33
This is not an urgent problem to solve
On the contrary, I think it's a good way to correct the wrong and stupid habits they've been having.
Forcing them to adopt the correct standard nomenclature

This crash only occurs in newer versions with "Vulkan"
Previous versions didn't crash
So I think it's partly caused by rewritten source code
Of course I don't have the power to fix it

I'm using Windows 10 22H2 19045.2604

**Comment by OV2** [comment] 2023-03-13 18:35
I tried it on a windows set to simplified chinese and still wasn't able to reproduce it. Did you try the most recent build?

**Comment by OV2** [comment] 2023-03-13 23:51
I think I've reproduced it, will take a closer look tomorrow.

**Comment by kingboxnt** [comment] 2023-03-16 02:54
Thanks for fixing the problem, it's great

Here is another problem with the error displaying Chinese
When using the Chinese name rom, the Chinese displayed in "Rom Info" is garbled
It doesn't cause crash, just some dissonance

Thanks again

![2023-03-16_104312](https://user-images.githubusercontent.com/53512332/225498287-d5f05137-edcc-4e27-98cc-ecc1fdb3848e.jpg)

**Comment by bearoso** [comment] 2023-03-16 21:08
The rom info dialog should be fixed now.

**Comment by kingboxnt** [comment] 2023-03-17 03:08
There are no words to express the excellent work of the professional, looking up to

**Closed** 2023-03-17 23:12 UTC
