### ISSUE TITLE
Snes9x 1.62.3 UNIX version ignores the default config file's content

### ISSUE THREAD

**Issue by TCH68k** [snes9xgit/snes9x#869] opened 2023-09-02 23:49 UTC
I have Snes9x 1.60 GTK2 installed, it has it's config file at `~/.snes9x/snes9x.conf`.
I've compiled the UNIX version of 1.62.3 and tried to run it. It tells me, it loaded the config automatically (it even shows it's path), but nothing is applied. Controls, window size, upscaling (4x, integer, no resampling or interpolation, just resize); none of them is applied.

**Comment by bearoso** [comment] 2023-09-03 16:05
The Unix version is an entirely different version. If you want to run the Gtk version barebones like the Unix version
1. Go into the Preferences, UI tab, and set the ESC key to "Quit Snes9x". 
2. Then go to the Display->Basic Settings tab and check the "Use fullscreen on ROM open" option. 
3. Then you can pass your ROM on the command line like `snes9x-gtk supermarioworld.sfc` and it'll open in fullscreen mode and close on ESC with no UI ever visible.

**Comment by TCH68k** [comment] 2023-09-03 23:02
I do not want to run the GTK version barebones. I want to run the UNIX version with the settings of the GTK version. Like integer upscaling in fullscreen.

**Comment by bearoso** [comment] 2023-09-09 21:42
Duplicate of #870.

**Closed by bearoso** 2023-09-09 21:42 UTC

**Comment by TCH68k** [comment] 2023-09-10 09:20
It is not a duplicate of #870, this not about the integer upscaling, but to get the content of the config file. What about the controls, etc.?

**Comment by bearoso** [comment] 2023-09-10 19:18
They use different config files because they're not the same program. The Unix port is unmaintained. If you want the it to have these features, add them and create a pull request.
