### ISSUE TITLE
Direct Input Gamepad Input Is Broken (windows 10 x64)

### ISSUE THREAD

**Issue by Nicholas-Steel** [snes9xgit/snes9x#129] opened 2016-10-12 09:30 UTC
Logitech F310 (Direct Input mode)
Snes9x v1.54 Win32_x64

Diagonal directions on the DPad would result in all directional input being ignored unless I specified the diagonals like this: http://imgur.com/tjHHs72

It then accepted Diagonal Up directions without issue but was still ignoring all directional input when pressing Diagonal Down directions.

Upon messing with the emulator software I came to the conclusion that the gamepad support is buggy, as seen in this video demonstration it is overwriting multiple inputs whenever I try to configure the Diagonal Downwards directions: https://www.youtube.com/watch?v=_j0sh-K7Px4

Gamepad input issues were first noticed while testing out Super Mario All-Stars (USA) which is the first game I decided to try out.

**Comment by OV2** [comment] 2016-10-12 19:56
There was a bug where assigning down left would assign the same key to down right, but other than that I can find no issues. If you use a DPad that is mapped as a POV hat it requires mapping the diagonals individually, since they are reported as extra buttons and not as a combination of the other four directions.

**Comment by Nicholas-Steel** [comment] 2016-10-13 04:25
That would explain the issue, cancelling each other out.

**Comment by Nicholas-Steel** [comment] 2016-10-13 04:34
Let me know when a new build is out.

**Comment by OV2** [comment] 2016-10-13 18:04
I made a testbuild here: http://www.s9x-w32.de/dl/testbuilds/snes9x_testbuild_13102016.zip

**Comment by jcdenton2k** [comment] 2016-10-13 21:37
I have the exact same controller and it works fine for me (without the test build) on Win7 SP1 x64 so it may be a change introduced between Win7 and Win10 or something particular to Win10 itself.

**Comment by Nicholas-Steel** [comment] 2016-10-14 07:31
jcdenton2k, you'll see here http://imgur.com/tjHHs72 the issue was intermittent as it did correctly configure the gamepad once, but when reconfiguring I could never get it to detect the gamepad properly again. This meant the issue was intermittent.

I also learned today that Super Mario Bros. was a very bad game to test the diagonal down direction. I figured the game would let you duck & slide if you pressed diagonally down but instead it seems to strangely ignore all directional input when on the ground. It responds to the across driection if you're mid-air though!

In Super Mario Bros 3. it will respond to across when on the ground while pressing diagonal down but it won't make you duck (so you can run across, this is an improvement over the first game). In Super Mario World it will make you duck if you press a diagonal down direction while on the ground.

OV2, the test build seems to work fine, I've recalibrated and restarted SNES9x x64 multiple times without issues.

**Comment by jcdenton2k** [comment] 2016-10-14 18:24
Or, you know, just leave the diagonals blank.  Like a real SNES controller.
I'm not sure why they are there except for macros to easily do special moves in fighting games.

I'm glad your 'issue' was fixed though.  Cheers.

**Comment by Nicholas-Steel** [comment] 2016-10-15 09:20
I don't really understand why the emulator can't recognize multiple button presses either and needs to special case the diagonals, but OV2 did explain above that it is for some reason required for POV inputs:

"If you use a DPad that is mapped as a POV hat it requires mapping the diagonals individually, since they are reported as extra buttons and not as a combination of the other four directions."

**Comment by jcdenton2k** [comment] 2016-10-15 23:51
Ok, after further testing you do need the diagonals for specific games like Street Fighter (and other fighting games) that require diagonal input for special moves.

I tried without the diagonals and the moves were significantly more difficult to pull off (but still worked).

I'm happy that this bug was fixed :)

**Comment by jcdenton2k** [comment] 2016-10-16 00:20
Tested with that new testbuild that @OV2 posted.
I can confirm the double-assign bug has been fixed.  I can also confirm that diagonal 'dead zones' still happen in both modes unless manually bound.  It takes a bit of fiddling on the Logitech F310 (because D-Pad is kinda crap) but it still works fine once it has been bound.

Thanks for the fix!

**Comment by Nicholas-Steel** [comment] 2016-10-16 09:03
I love the floating DPad for the F310, it's great for games that do not rely on rolling the DPad around in a circular motion and as such is perfect for the games that I like to play (Bad for fighting games of course).

Thanks for confirming the test build fixes the issue.

**Comment by jcdenton2k** [comment] 2016-10-20 03:15
**@Nicholas-Steel** 
Thank YOU for explaining what the issue was and alerting me to a bug that I didn't even take into consideration.  I use a Logitech Precision Pro (non-analog) gamepad for my retro gaming (8-bit and 16-bit) so I didn't even notice the issue for the longest time.

Since the issue is resolved, maybe we should close the issue as 'fixed' and have the new fix merged into the 'master' branch as soon as possible.

**Comment by bearoso** [comment] 2016-10-20 15:25
It should be fixed and merged to master already. (6f2fe7e52b7806596235080ea108ab8f4e743a4b)

**Closed by bearoso** 2016-10-20 15:25 UTC
