### ISSUE TITLE
Commits But No Releases?

### ISSUE THREAD

**Issue by ghost** [snes9xgit/snes9x#99] opened 2015-12-15 07:28 UTC
Hi,

I see there have been commits done this year, but when I look at the releases, no version updates in 4 years.

Are there going to be any other new stable releases coming?

thank you

**Comment by akien-mga** [comment] 2016-01-12 12:06
As the maintainer of snex9x-gtk for Mageia, I'd be interested to see a new release too :)

**Comment by OV2** [comment] 2016-01-12 18:20
The main issue is that our OSX developer has been absent for a while now, and there has also been no real emulation work done in a while. So we'd have to release without that platform.

**Comment by akien-mga** [comment] 2016-01-12 21:14
For an open source projects it's fine IMO if you can provide binaries for all platforms at once. The new release doesn't have to be a huge thing, it can be just a source tarball + binaries for the platforms you can handle (win32 and linux64 would be fine I guess), and let Linux packagers do their work to update their snes9x packages.

And if some regressions are found, you shouldn't hesitate to do a point release shortly after the new one - release early, release often! goes the saying :)

**Comment by Geyup** [comment] 2016-01-14 03:43
@OV2 is there going to be any new development then going to pick up? Since you mention there's been no real emulation work done in a while?

**Comment by Geyup** [comment] 2016-08-01 07:29
I'm starting to think working on a core for libretro is the way to go?

Hmm

**Comment by OV2** [comment] 2016-08-01 07:35
There are already multiple snes9x cores available for libretro, even this repository contains one.

The windows testbuilds are put up by me every time something relevant is committed, which has not been the case since oct 11. That build also contains both 32 and 64bit.

**Comment by akien-mga** [comment] 2016-08-01 07:40
Back to the topic of rolling out a new release, I still think it might make sense to label some recent state as "stable" release with a tag, since the current latest releases dates back to 2011. Even if the OSX packager is not around, it's perfectly fine to distribute Windows and Linux binaries for a 1.54 version, and only 1.53 binaries for OSX - that might even motivate new OSX contributors to help make binaries.

A new release means many new eyes looking as snes9x and seeing that the project is still alive; even if the changelog contains mostly some bug fixes here and there or buildsystem improvements, it's definitely worth it.

Now, I'm not really familiar with the current developments of snes9x so I can't tell if the current master branch would be release ready or in the middle of a big refactoring, so of course it's your call :)

*Release early, release often* is always the way to go for a community-driven project.

**Comment by Geyup** [comment] 2016-08-01 08:15
@ov2 ok thanks

**Comment by jcdenton2k** [comment] 2016-08-01 13:58
@OV2:

I've gotten in touch with Orphis and they're willing to host automated builds for SNES9X both Windows and Linux releases on 32-bit and 64-bit.

They need a project maintainer to contact them, website is here:
http://buildbot.orphis.net/

They already do builds for PCSX2 and PPSSPP so their bot does a pretty awesome job of it.  It would also make it significantly easier for our Windows users to download SNES9X from a safe and reliable location.

We could also put an official notice on the build page that SNES9X has NO official Android or iOS builds and that any such builds on mobile platforms are unauthorized license-violations and should be reported to Google/Apple respectively.

Awareness is a useful thing and would reduce the team's load on answering tech support questions from clueless people who didn't know about it.

**Comment by jcdenton2k** [comment] 2016-08-01 14:03
For everyone else, here's something to enjoy while we wait on updates! :8ball: 
https://www.youtube.com/watch?v=1SQTgG1y9lE

**Comment by jcdenton2k** [comment] 2016-08-02 01:15
Ok so after digging through the commits I've figured out what @OV2 was talking about.  All commits since the October 11 2015 test build have been to the unix and x11 files and don't benefit the Windows build at all.

That's good to know, but it wouldn't hurt to release a new 'stable' version rather than trying to get people to find the link to the test builds.  Those builds aren't exactly super easy to find but I did link it in a previous post here so perhaps that might help.

In the meantime, it may be more useful to have an updated new 'stable' version and just compile an updated binary for linux & windows both 32-bit and 64-bit.

For the future it may be useful to backport some changes/updates from the retrolib SNES9X-Next version if possible.

**Comment by jcdenton2k** [comment] 2016-08-04 03:19
@OV2 I'd like to know if someone on the team can give the green light to Orvis to have their buildbot auto-create updated builds from this github for snes9x for Win32/64 and Linux32/64.

Having a nice centralized 'official' download location outside of the SNES9X forums and random 3rd-party mirrors would instill more confidence in people who want to use this emulator over other inferior ones.

**Comment by bearoso** [comment] 2016-08-04 03:47
I don't see any reason to need to ask for permission to do automated builds. It's fine by me.

**Comment by OV2** [comment] 2016-08-04 15:16
I also don't have any problem with automated builds. I'll still upload my testbuilds when there are significant changes, but that does not prohibit any automated build.

**Comment by jcdenton2k** [comment] 2016-08-05 01:00
@bearoso @OV2 I've forwarded your comments and a link to this post to Orphis; thank you both for responding :)

**Comment by Orphis** [comment] 2016-08-06 20:28
I'll try to setup some CI builds later then.
I usually ask for permission to make sure that you know about it. Some people have a habit of building lots of emulators to make money out of it and I don't want to be seen as one of them!
Any information about the packaging of the software? What do you prefer?

**Comment by jcdenton2k** [comment] 2016-08-07 00:25
@Orphis 

I guess I'll poke my head back in here.  I'm perfectly ok with just a straight-up automated build from the github for Windows x86 and x64 as well as Linux x86 and x64.  I figure anyone who wants customization tailored to their computer can compile it from source themselves.

Taking a very quick glance through the CPU Architecture coding, I didn't notice any way to optimize specifically for any CPUs so a 'generic' compile should work just fine.

**Comment by jcdenton2k** [comment] 2016-08-08 16:17
Since Orphis will be doing automated builds based on Github releases, can we close this issue now?

**Comment by akien-mga** [comment] 2016-08-08 16:20
As a Linux packager, I would still like to have a tagged upstream release to package.

**Comment by jcdenton2k** [comment] 2016-08-08 16:24
@akien-mga 

Feel free to get in touch with Orphis and help them with getting the automated linux builds (x86 and x64) ready to go.  Build documentation is a bit sparse so it couldn't hurt :)

**Comment by akien-mga** [comment] 2016-08-08 16:45
> Feel free to get in touch with Orphis and help them with getting the automated linux builds (x86 and x64) ready to go. Build documentation is a bit sparse so it couldn't hurt :)

Well as of 1.53 the build process on Linux was not too difficult: http://svnweb.mageia.org/packages/cauldron/snes9x/current/SPECS/snes9x.spec?view=markup
Just replace `%configure2_5x` by `./configure --prefix=/usr/local`, `%make_build` by `make -jX` and `%make_install` by `make install DESTDIR=/where/you/want/it/for/packaging`.

Now, those are just the steps to build on Linux and install the contents somewhere on the builder's system.
Creating portable binaries is more involved work than that, but apart from giving some tips if needed, I don't particularly plan to get much involved; I'm quite busy with the other open source projects I work on, and I'm sadly not too fond of snes9x's freeware license (though I understand that it's likely impossible to get rid of it now) so wouldn't want to spend too much time on it.

**Comment by jcdenton2k** [comment] 2016-08-08 16:55
You mean this license?

> Permission to use, copy, modify and/or distribute Snes9x in both binary and source form, for non-commercial purposes, is hereby granted without fee, providing that this license information and copyright notice appear with all copies and any derived work.
> 
> This software is provided 'as-is', without any express or implied warranty. In no event shall the authors be held liable for any damages arising from the use of this software or it's derivatives.
> 
> Snes9x is freeware for PERSONAL USE only. Commercial users should seek permission of the copyright holders first. Commercial use includes, but is not limited to, charging money for Snes9x or software derived from Snes9x, including Snes9x or derivatives in commercial game bundles, and/or using Snes9x as a promotion for your commercial product.

So I don't see how that license is terrible.  As long as you aren't charging money or including it in paid game bundles then it is good to go.  You DO realize that GPL'd code is frequently violated without anyone giving a damn (and even non-GPL'd code) so open-source in general is in danger without some legal 'teeth' to prevent obvious assholes like Hyperkin to use code without source code releases as mandated in their RetroN5.  People don't even know the RetroN5 is just a portable emulator box that functions as a very pricey cart-dumper and then runs the ROM that is dumped.

That said, that could be part of the reason nobody really wants to touch this with a 20 foot pole lately.

I feel RetroArch is on the right track with many things but they still run into issues when they create custom core fixes but don't send those changes to upstream.

**Comment by akien-mga** [comment] 2016-08-08 17:47
Well I don't want to start a discussion about licensing here, it would be quite off topic, and I'm pretty sure there are tons of interesting discussions about this in other places already. But yeah, the "for PERSONAL USE only" clause, just like the NC clause of Creative Commons licenses, makes the Snes9x license effectively a "nonfree" license (i.e. not FSF-free, not OSI-free, not DFSG-free, not Fedora packaging guidelines-free, and hence not free for my distro Mageia either).

The license itself is not a problem for users and developers of snes9x, as the "open source BSD/MIT-like as long as it's for personal use" license covers the use case of 99.99% of the snes9x target users. Still, from the standpoint of a Linux distribution trying to promote in priority fully free projects, and wanting to keep the possibility for being distributed on paid support (DVDs, magazines, etc.), such a license has to be categorized as nonfree and the packaged binaries distributed as such. But yeah, in the open source community, a custom license will always be a hindrance. Now, I'm pretty aware that it's probably impossible to change the license of snes9x even if there was a will to do so; and I'm not asking for it either, just saying that I'm not interested enough to start contributing a lot ;)

**Comment by jcdenton2k** [comment] 2016-09-19 18:18
Been a bit busy.  Haven't seen much activity here so I'll throw something out.

1 - Digital Distribution is the new thing.  Paid support is typically done with corporate clients rather than individual users.  Aka who the hell uses DVDs and Magazines anymore?  ;)

2 - If certain distros only strictly absolutely want to adhere to certain principles then they are welcome to do so.  However they should realize that they won't get everyone else to fall in line with them right away (or at all).  When it comes to gaming DRM look at Steam vs GoG and although both offer similar services and sales and pricing, GoG has the DRM-free motto yet it still doesn't get anywhere near the exposure/attention that Steam does.

**Comment by qwertymodo** [comment] 2017-03-23 18:57
Any update on a release?  I have gotten a lot of people asking me about MSU-1 builds, and I'm fine hosting the test builds that I have, but those builds had some things disabled because I wasn't able to acquire the dependencies, like FMOD, and it would just be nice to actually have a release instead of pointing people to my own personal server like that.

**Comment by jcdenton2k** [comment] 2017-04-21 18:05
There hasn't been any updates on this in a while.  I believe Orphis received the necessary permissions but I don't see SNES9X available for download from their buildbot server.

http://buildbot.orphis.net/

So things were stalled somewhere and something happened or didn't happen privately that nobody wants to discuss.  Oh well :(

**Comment by OV2** [comment] 2017-04-21 22:05
I've made a new [testbuild](http://www.s9x-w32.de/dl/testbuilds/snes9x_testbuild_17042017.zip) a few days ago with the msu1 and bsx changes.

**Comment by Orphis** [comment] 2017-04-21 22:44
Sorry, I'm super busy with real life and have been traveling a lot! I need to find a bit of time to do it soon.

**Comment by Orphis** [comment] 2017-04-25 22:14
So, I've spent a little bit of time trying to build it and the process is quite bad.

I suggest you start by modernizing your codebase and structure:
- Don't require libraries outside of the project tree. So copy zlib and libpng sources in there and use that on Windows. It should just work.
- Remove reprecated / non-free dependencies like cg and FMOD.
- Build as Unicode only. Why is that even a choice?
- Make it build with latest Windows 8.1 SDK (or Win10 SDK, but then deprecate WinXP and tell users to use an old build).

**Comment by qwertymodo** [comment] 2017-04-25 23:23
- Don't require libraries outside of the project tree.

I agree, that in particular could use some refactoring.  We could move 3rd party libraries into a 3rdparty directory inside the project tree.  And when possible (e.g. zlib), we could even use git submodules so the library could just be checked out with a recursive clone.

- Remove reprecated / non-free dependencies like cg and FMOD.

Only if you can do so without losing functionality, i.e. replace them (GLSL).  There are compile-time switches for a reason, if you can't build against those dependencies, then just disable them.

- Build as Unicode only. Why is that even a choice?

This one, I agree with, if the Unicode build works, why bother maintaining both?

- Make it build with latest Windows 8.1 SDK (or Win10 SDK, but then deprecate WinXP and tell users to use an old build).

Again, this would remove functionality without any gain.  It's not any extra work to support WinXP, no need to drop it.

**Comment by Orphis** [comment] 2017-04-26 00:03
The default project on Windows defines FMODEX as available, this should be removed. What does FMOD(EX) add that regular APIs don't support already?

How many WinXP users do you have? How many will require a new version and won't be satisfied with the current version? By raising the minimum version, you can be sure some APIs are available and thus remove old backends like DirectDraw since you know Direct3D will be available, or even DirectAudio / XAudio2 since you could use WASAPI instead.

**Comment by OV2** [comment] 2017-04-26 10:46
- Moving the library locations is fine by me, it was probably originally like this to share it with other projects.
- FMOD/Ex can be removed, I have no problem with that.
- The non unicode targets are a leftover from when I added unicode support, since it was somewhat of a hack. Can theoretically be removed.
- Win 8.1 SDK should be possible.
- Removing CG is not an option at the moment unless someone implements an alternative for both GL and D3D

**Comment by jcdenton2k** [comment] 2017-04-29 15:42
I'm starting to see why certain things are the way they are and why so few contributors want to help this particular emulator.  Yikes :(

That said, perhaps @Orphis might want to consider poking the RetroArch people to port their forked SNES9X build to an actual exe build since it includes the SuperFX speed hack.  I'm not 100% on how they maintain their cores but it may be easier to build against than trying to do it directly here.

**Comment by bearoso** [comment] 2019-03-09 23:50
Released a bunch of times.

**Closed by bearoso** 2019-03-09 23:50 UTC
Labels: meta
