### ISSUE TITLE
snes9x-gtk [xcb] Unknown request in queue while dequeuing

### ISSUE THREAD

**Issue by unassumingbadger** [snes9xgit/snes9x#676] opened 2020-10-09 22:31 UTC
OS Raspbian 2020-08-20
Kernel  5.4.51-v7l+

--- SIGWINCH {si_signo=SIGWINCH, si_code=SI_KERNEL} ---
restart_syscall(<... resuming interrupted poll ...>) = 1
recvmsg(3, {msg_name=NULL, msg_namelen=0, msg_iov=[{iov_base="#\203\372\0\v\0\0\0\t\0\3\0\353Y\26\0\3\0\0\3v\3\0\$
poll([{fd=3, events=POLLIN}], 1, -1)    = 1 ([{fd=3, revents=POLLIN}])
recvmsg(3, {msg_name=NULL, msg_namelen=0, msg_iov=[{iov_base="\34\0\372\0\7\0\300\1?\1\0\0\354Y\26\0\0\0\0\0\0\0\$
poll([{fd=3, events=POLLIN}], 1, -1)    = 1 ([{fd=3, revents=POLLIN}])
recvmsg(3, {msg_name=NULL, msg_namelen=0, msg_iov=[{iov_base="\21\0\376\0\26\0\300\1\26\0\300\1\0\0\0\0\0\0\0\0\0$
poll([{fd=3, events=POLLIN}], 1, -1)    = 1 ([{fd=3, revents=POLLIN}])
recvmsg(3, {msg_name=NULL, msg_namelen=0, msg_iov=[{iov_base="\34\0\t\1\7\0\300\1)\1\0\0\34Z\26\0\0\0\0\0\0\0\0\0$
poll([{fd=3, events=POLLIN}], 1, -1)    = 1 ([{fd=3, revents=POLLIN}])
recvmsg(3, {msg_name=NULL, msg_namelen=0, msg_iov=[{iov_base="\34\0\16\1\7\0\300\1'\0\0\0\34Z\26\0\0\0\0\0\0\0\0\$
poll([{fd=3, events=POLLIN|POLLOUT}], 1, -1) = 1 ([{fd=3, revents=POLLOUT}])
writev(3, [{iov_base="\227\0\1\0", iov_len=4}, {iov_base=NULL, iov_len=0}, {iov_base="", iov_len=0}], 3) = 4
poll([{fd=3, events=POLLIN}], 1, -1)    = 1 ([{fd=3, revents=POLLIN}])
recvmsg(3, {msg_name=NULL, msg_namelen=0, msg_iov=[{iov_base="\1\0\22\1\0\0\0\0\2\0\2\0\0\0\0\0\0\0\0\0\0\0\0\0\0$
[xcb] Unknown request in queue while dequeuing
[xcb] Most likely this is a multi-threaded client and XInitThreads has not been called
[xcb] Aborting, sorry about that.
snes9x-gtk: ../../src/xcb_io.c:165: dequeue_pending_request: Assertion `!xcb_xlib_unknown_req_in_deq' failed.
futex(0x262a624, FUTEX_WAIT_PRIVATE, 2, NULL <unfinished ...>
+++ killed by SIGABRT +++

[out.txt](https://github.com/snes9xgit/snes9x/files/5357897/out.txt)

**Comment by bearoso** [comment] 2020-11-04 18:15
Duplicate of #678.

**Closed by bearoso** 2020-11-04 18:15 UTC
