### ISSUE TITLE
Feature request: always hide mouse cursor in fullscreen mode

### ISSUE THREAD

**Issue by etking** [snes9xgit/snes9x#31] opened 2013-05-11 23:01 UTC
Would be really great if this was possible because the mouse cursor is always visible.

**Comment by vgturtle127** [comment] 2015-09-27 05:36
#86 may be related, but I have a feeling this will be an issue that is hard to debug...

**Comment by SwinglesMan** [comment] 2015-10-13 17:08
if this gets implemented, don't override the other one (mouse hide while inactive). Make them separate settings.

**Comment by bonimy** [comment] 2017-08-26 18:42
This issue seems to be a duplicate of #86, which was resolved. Recommend closing.

**Comment by qwertymodo** [comment] 2017-08-29 18:55
Yep, duplicate of #86

**Closed by qwertymodo** 2017-08-29 18:55 UTC
Labels: app-ui, feature
