### ISSUE TITLE
MSU not recognized if in a zip file

### ISSUE THREAD

**Issue by Swagman89** [snes9xgit/snes9x#185] opened 2017-04-09 23:38 UTC
I know we got MSU-1 sound working on here a few months back and the current way to enable that is to dump all the audio tracks+rom+msu file in a folder. That all works fine as long as the folder is not zipped. I think there should be an update to whatever allows us to use a zipped rom to have it look for an MSU file as well to enable the MSU audio so we can zip these files still and save space versus throwing them all in a folder. 

Thoughts?

**Comment by qwertymodo** [comment] 2017-04-09 23:45
Pretty sure OV2 already implemented that, but it isn't in any released builds yet. You'll just have to wait for 1.55.

On April 9, 2017 4:38:52 PM PDT, Swagman89 <notifications@github.com> wrote:
>I know we got MSU-1 sound working on here a few months back and the
>current way to enable that is to dump all the audio tracks+rom+msu file
>in a folder. That all works fine as long as the folder is not zipped. I
>think there should be an update to whatever allows us to use a zipped
>rom to have it look for an MSU file as well to enable the MSU audio so
>we can zip these files still and save space versus throwing them all in
>a folder. 
>
>Thoughts?
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/snes9xgit/snes9x/issues/185

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by Swagman89** [comment] 2017-04-09 23:45
Is there a nightly I could pull that in from or do you know what was changed so I could perhaps compile it myself?

**Comment by qwertymodo** [comment] 2017-04-10 00:00
There's a branch specifically for it on github, MSU-zip or something like that, I don't remember exactly.

On April 9, 2017 4:45:38 PM PDT, Swagman89 <notifications@github.com> wrote:
>Is there a nightly I could pull that in from or do you know what was
>changed so I could perhaps compile it myself?
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/snes9xgit/snes9x/issues/185#issuecomment-292822111

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by Swagman89** [comment] 2017-04-10 00:12
I also just realized that I opened this under the mainline instead of the libretro core which is where it should have been...

**Comment by qwertymodo** [comment] 2017-04-10 00:51
Duplicate of https://github.com/snes9xgit/snes9x/issues/155

**Closed by qwertymodo** 2017-04-10 00:51 UTC
