### ISSUE TITLE
Release version 1.54

### ISSUE THREAD

**Issue by bearoso** [snes9xgit/snes9x#124] opened 2016-10-07 17:34 UTC
I'm at a point where I'm satisfied with the stability of the Gtk+ port. It could use a couple of features, but I'd like to get the eternally delayed 1.54 out finally before any more tinkering.

OV2, what is your opinion on the state of the Windows port? I know you mentioned fixing a Sufami Turbo issue on the forums, so that is a TODO, but are you otherwise satisfied with the stability and OK with pushing out a release? 

I'm no longer comfortable doing binaries for linux systems, given its own form of "dll hell" that has developed. So I'd just do a source release. That simply involves running autogen.sh in the gtk directory to bootstrap configure, then building the tarball. The unix release has configure in git, so that's unnecessary there. The actual binaries would then be built by the distributions.

Given zones' MIA status, we'd have to let the Mac port be stagnate for this one.

**Comment by bearoso** [comment] 2016-10-07 17:36
We also need to update the copyright to add something about byuu's S-SMP core, and your Windows port one. I've already bumped the version number and our respective core copyrights.

**Comment by bearoso** [comment] 2016-10-07 17:55
Ok, copyrights are updated.

**Comment by OV2** [comment] 2016-10-07 19:01
Besides the Sufami Turbo fix I'd want to finally merge in some of the libretro changes from their repo. I'll see if I can also do that this weekend. Other than that the windows port should be fine, but maybe I'll switch the project to vs2015 before a release.

I'll send a pm to zones to see if he is around at all. We could also try contacting ryan if he can then update the s9x homepage, it seems some work has been done there.

**Comment by OV2** [comment] 2016-10-07 19:12
One thing I noticed when looking into the "Hook" issue was that we still have no working APU debugger, but I guess that shouldn't really matter for a release.

**Comment by bearoso** [comment] 2016-10-07 22:43
I had the APU debugger working when I first attached byuu's core, and it was fairly easy. I don't know why I reverted that. The code is there to be hooked up, but you're right, it shouldn't matter for an end-user release.

**Comment by joepogo** [comment] 2016-10-08 19:02
When you say hook issue OV, is that the one i reported? I put the line to true and it is still showing a bunch of q's on the screen.

**Comment by OV2** [comment] 2016-10-08 20:40
Multicart fix and libretro changes are in, the visual studio change is also done. No answer from zones so far.

Do you want to take a look at the rewind pull request? I think I also added that to the unix version when I pulled it over from retroarch, would be nice if it is in all versions. But also not a necessity I'd say.

**Comment by bearoso** [comment] 2016-10-09 00:14
Yeah, the pull request uses it unconditionally, and I wanted to make sure it didn't allocate anything if it wasn't going to be used, especially not by default. I'll look at it and try to get it in.

**Comment by bearoso** [comment] 2016-10-09 03:11
Ok, the rewind stuff is in and working.

**Comment by jcdenton2k** [comment] 2016-10-09 04:49
Awesome!  Finally a v1.54 release!  I'm hoping we can get binaries for the Windows-side since it is more difficult to compile source code on Windows (and costly to boot).

**Comment by roflcopter777** [comment] 2016-10-09 06:55
Yes, that would be the Super FX2 (real name GSU-2-SP1) used in Star Fox 2, Yoshi's Island and a few others I can't think of right now; can't wait to see this released.  Overclocking would be nice, but not a deal-breaker if not included.

**Comment by bearoso** [comment] 2016-10-09 15:04
I'm pretty sure binaries for Windows are guaranteed. 

And I'm sure that retrolib 'hack' is just that, a hack. It overclocks the SuperFX _faster_ than what the SuperFX2 ran at to make StarFox 2 more playable. We're generally against backpedaling accuracy with speed hacks. I know Snes9x's C SuperFX core is actually a little glitchy compared to the old ASM core, so it might be due for some fixes in the future.

**Comment by roflcopter777** [comment] 2016-10-09 15:09
Again, do what you need to do, if it's not in the Windows/Libretro binary, no biggie, getting it ready for release and ensuring it's ready is more vital; keep up the good work :)

**Comment by jcdenton2k** [comment] 2016-10-09 16:02
I'd rather the release not be delayed just for the sake of including that speed hack.

However, that being said I wouldn't mind future versions possibly including it as an option.  Again, following the PCSX2 model of allowing the end-user to decide on sacrificing 'accuracy' for a smoother/faster gameplay experience for certain (SuperFX) games.

**Comment by bearoso** [comment] 2016-10-09 20:46
Anything else still missing?

**Comment by OV2** [comment] 2016-10-09 22:15
I don't think so. I'll do some tests with older windows versions tonight, then everything is ready on my end.

**Comment by bearoso** [comment] 2016-10-10 01:50
Heads-up: you've still got some version numbers to bump in the win32 directory that I didn't want to mess with.

I also assume we should write a changelog/update changes.txt.

**Comment by OV2** [comment] 2016-10-10 19:22
Ok, testing went fine. I've updated the version number for the exe, couldn't find any others. As for the changelog, I added everything I could remember and find in the commits that seemed worth mentioning.
I also messaged ryan if he has frontpage access, we'll see if he responds.

**Comment by bearoso** [comment] 2016-10-10 21:25
I've rolled a source tarball, and put it at https://sites.google.com/site/bearoso/
If there's anything wrong, let me know.

Once you've made your binaries, I'll upload them there as well.

**Comment by OV2** [comment] 2016-10-10 22:37
I've uploaded them here: http://www.s9x-w32.de/dl/
The binaries are for the GUI and the libretro dlls. The cg dlls are still the same as last time and still optional.

**Comment by bearoso** [comment] 2016-10-10 23:08
Everything is copied to my site, as well.

**Comment by roflcopter777** [comment] 2016-10-10 23:43
Excellent work on the new release, guys :)

**Comment by gitgiit** [comment] 2016-10-11 00:06
Was there going to be 64-bit build too, like with your testbuilds OV2?

**Comment by OV2** [comment] 2016-10-11 09:12
I definitely built it yesterday - it seems I forgot to upload the zip file... I'll do that after work today.

**Comment by OV2** [comment] 2016-10-11 18:26
I did upload the x64 version, but the zip file was named 1.53... should both be there now.

**Comment by jcdenton2k** [comment] 2016-10-11 18:35
WOHOO!  Time to finally update SNES9X!

**@OV2 @bearoso**
Any information on whether or not we'll get stuff like the SuperFX speedhack implemented as an end-user selectable option?  Would also be interesting if the GSU-2-SP1 speed for StarFox 2 could be used as a baseline (or even a speed slider) so that players could have some control over playing the original StarFox SNES title at a playable framerate.

Don't get me wrong.  It was fantastic for the time but ~15 FPS is cringe-worthy today and barely playable.  Getting it up to even 25 or 30 fps would be much more tolerable and a speed slider for the SuperFX chip would be a dream :)

**Comment by Pat86** [comment] 2016-10-11 19:41
Just of of interest, is the random crash on the PAL Version of Secret of Evermore fixed in this version?

**Comment by bearoso** [comment] 2016-10-11 19:53
The crash in SoE may or may not be better or even worse. I suspect DMA timings are at fault, causing a desync of S-CPU and S-SMP.

jcdenton2k: I understand your desire for said option, but that's more of the philosophy of the Snes9x-next guys. You're always able to use Retroarch or something for just that one game and mainline Snes9x for anything else if you prefer the Snes9x UI or something.

**Comment by qwertymodo** [comment] 2016-10-11 19:54
Just to be clear, the GSU-2 (SuperFX 2) does NOT run faster than the GSU-1.  There is a clock divider register that allows both to run at half-speed, and I have confirmed on real hardware that they run identically in both modes.  I was not able to test the MARIO-CHIP revision found on Star Fox 1, but I was able to test both GSU-1 and GSU-1A revisions and confirmed it on both.  Yes, overclocking the GSU will allow the game to run more smoothly, but this is NOT HARDWARE ACCURATE.

See:
https://www.youtube.com/watch?v=6HF8yfhWJJM
https://www.youtube.com/watch?v=npmAteg7BPA

**Comment by jcdenton2k** [comment] 2016-10-11 20:40
@qwertymodo 
I appreciate the explanation & videos.  Thanks!
I was wondering if cheat codes could be enabled to manipulate the addresses within memory to enable/disable these particular modes for those who like to experiment with such things.  I notice one of your videos has an address listed but I'm unsure if it is a RAM address (aka able to be done with a cheat code) or a ROM address (needs a patch to enable it).

If needed, I'm hoping to use this information to create a 'speed up' rom mod for StarFox 1 for those that would prefer smoother gameplay.  This would allow the end-user to customize the experience to their preferences without requiring additional work from the SNES9X devs or breaking the accuracy options of SNES9X itself.

**Comment by qwertymodo** [comment] 2016-10-11 20:45
If you're referring to 0x018354: 0x01 -> 0x00, that's a ROM patch, and the address is a direct file offset, not the SNES mapped address.  I'm pretty sure Star Fox 1 also sets the clock divider to high-speed mode, so a ROM patch won't make any difference.  The only option to increase the framerate would be to overclock the chip, which actually speeds up the entire game, it doesn't just smooth out the display.

**Comment by bearoso** [comment] 2016-10-11 22:02
OV2, you want to do the announcement forum post?

**Comment by bearoso** [comment] 2016-10-11 22:29
Updated the source tarball to fix the libretro issue. Doesn't concern the binaries. OV2, you should copy the new one over.

**Comment by OV2** [comment] 2016-10-11 22:40
Thanks, copied it. I can make a post after work, it's 1AM here. Ryan hasn't answered so far, not sure how often he checks the forum.

**Comment by DaMan69** [comment] 2016-10-12 17:02
Tag please, 1.53/1.52 have one.

**Comment by bearoso** [comment] 2016-10-12 17:54
It's tagged. If there are any more problems, they go into a 1.54a or 1.54.1.

**Comment by OV2** [comment] 2016-10-12 20:01
I made the forum post, hopefully ryan will come around to make it sticky.

**Comment by jcdenton2k** [comment] 2016-10-13 21:24
@qwertymodo 
Thank you for taking the time to post the details of that data.  I'll pass it along to the rom modding communities I work with who've been (attempting) to work on such patches for a while now.  It is always awesome to get actual hardware info about these kinds of things.

**Comment by qwertymodo** [comment] 2016-10-13 21:48
@jcdenton2k Star Fox 1 runs on the earliest revision of the GSU (labeled MARIO-CHIP on the PCB), which may or may not support the clock select register $3039.  I was unable to test it, due to being unable to get Star Fox 2 running on a Star Fox 1 board.  It's been over a year since I ran those tests, but I think it had something to do with the MARIO-CHIP not supporting the larger SRAM chip that Star Fox 2 required.  However, if you were to run Star Fox 1 on a GSU-1 or GSU-1A board, then at least I can confirm that it would support it, though IIRC the entire game runs faster, as the main game code doesn't have any kind of frame limiting and just runs as fast as possible, with the SuperFX as the bottleneck (at least that's the behavior I've seen with overclock mods, I would assume that you would experience the same result with the clock select register).  I just ran a quick debug session, and Star Fox 1 does not write to $3039 at all (at least not during the intro video, menu screen, or the first few seconds of the first mission).  So, if you want to try it out in an emulator, just find somewhere early in the game startup sequence and add in a simple lda #$01; sta $3039; and see if that makes any difference.  One of these days I may try it out in hardware, but we'll see.  I don't have any way of reprogramming it in-circuit, so I have to pull the chip, clean it, throw it in a socket, and then re-solder it, so it's a real pain...

**Comment by jcdenton2k** [comment] 2016-10-13 21:51
Zophar updated but only with the x86 version.
Ipher hasn't updated their links.
Emulator Zone also hasn't updated.

Seems http://www.s9x-w32.de/dl/ is the most direct route.  Might be worthwhile to post some official 'direct' download links for those who aren't aware of how to navigate directories directly?  Why not include bearoso's website in the mirrors?

Also the source link on that website should have -src in the file name like the other versions to maintain consistency.

> Website: http://www.snes9x.com/
> Better website: https://sites.google.com/site/bearoso/
> 
> (Use 32-bit for WinXP, 64-bit for anything later)
> 32-bit: http://www.s9x-w32.de/dl/snes9x-1.54-win32.zip
> 64-bit: http://www.s9x-w32.de/dl/snes9x-1.54-win32-x64.zip
> 
> (For technical users only)
> Source: http://www.s9x-w32.de/dl/snes9x-1.54.tar.bz2
> Libretro Core: http://www.s9x-w32.de/dl/snes9x-1.54-libretro-win.zip

**Comment by jcdenton2k** [comment] 2016-10-13 21:53
Would also love to see a proper ReadMe.md for the Github main page as well as some updated clear build instructions for the various ports (at least Windows/Mac/GNULinux)

**Comment by OV2** [comment] 2016-10-13 22:03
We do not have direct access to the snes9x frontpage. Those are the mirrors that were put up the last time.

I'll try to update the build txt file this weekend for the vs2015 build.

**Comment by roflcopter777** [comment] 2016-10-13 22:11
Who does have access to the front page? Surely, the one who does can be contacted and then the privilege given to you guys?

**Comment by bearoso** [comment] 2016-10-14 18:12
OV2, I think there's been enough problems to do a 1.54.1 release. I'll bump the version numbers. Let me know if there's anything you want to get in before that.

**Comment by OV2** [comment] 2016-10-15 00:24
I just updated the build instructions txt file for win, other than that I have nothing at the moment.

**Comment by bearoso** [comment] 2016-10-15 02:21
Ok, I've tagged 1.54.1 and uploaded a tarball to my site. I'll copy over the Win32 port files when you make them.

**Comment by OV2** [comment] 2016-10-15 15:44
Uploaded the binaries and copied the source tarball over.

**Comment by bearoso** [comment] 2016-10-15 16:37
Do you want to update the forums post with a new small block for the 1.54.1 changelog and just alter the numbers in the title?

**Comment by OV2** [comment] 2016-10-15 23:15
I can no longer edit the first post so I added the log at the end. But I've got a response from Ryan, maybe he can fix that.

**Closed by OV2** 2016-10-15 23:15 UTC

**Comment by kethinov** [comment] 2016-10-16 22:50
> Given zones' MIA status, we'd have to let the Mac port be stagnate for this one.

Out of curiosity, is this just a simple matter of someone doing a build, or is there nontrivial work involved in integrating the changes from this repo into the Mac port?

**Comment by bearoso** [comment] 2016-10-16 23:28
Nontrivial work. 

(just noticed it says stagnate instead of stagnant)
