### ISSUE TITLE
Weird MSU-1 Glitch Crashes Game upon Song Finishing

### ISSUE THREAD

**Issue by felixrodent** [snes9xgit/snes9x#778] opened 2022-08-10 23:43 UTC
Hello! I am felix.rodent. I am making an Earthbound ROM Hack, and I've discovered that one of my MSU-1 songs can crash the SNES9x Emulator. I have to go to Task Manager to kill it because it says "Not Responding". 

I have a very good computer so it is not hardware related, and it only happens when this song ends. 

The song in question is the first one that plays when loaded into the game, due to the game having you right next to the enemy, initiating the battle. (The battle music is on the 3 guys in poses of I, K, and R)

If you wait 2 minutes for the song to "end", it just crashes the whole emulator.

Attached is the patched rom, pcm files, and other stuff you need to see if this is an issue on anyone else's end.
[Github.zip](https://github.com/snes9xgit/snes9x/files/9305111/Github.zip)

**Comment by qwertymodo** [comment] 2022-08-10 23:47
I don't have the ability to look at it right now, but the only reason I can think of for the emulator to crash, especially at the end of a song, would be if the song has an invalid loop point beyond the end-of-file. This should never happen, but I also don't think we bother to check for it when we seek the file stream. Might be worth adding in a check. I'm not sure whether the preferred behavior would be to halt playback, or just loop back to the start of the file. Probably the latter.

**Comment by felixrodent** [comment] 2022-08-11 00:08
I think looping back to the start would be better than halting playback perhaps.

**Comment by OV2** [comment] 2022-09-01 13:23
The issue is as qwertymodo guessed, the loop point is after the end-of-file, so it is infinitely trying to loop back. I'd also simply start at zero in this case.

However I also got a lot of msu resampler underflows when trying with this rom, which seems weird. I'll have to find some more time to look at it.

**Comment by OV2** [comment] 2022-11-06 14:16
Finally had time to look at this again, I've committed the change to loop back to the beginning for invalid loop points (loop point > current position).

**Closed by OV2** 2022-11-06 14:16 UTC
