### ISSUE TITLE
Tons of GTK errors on Debian

### ISSUE THREAD

**Issue by andoruB** [snes9xgit/snes9x#76] opened 2015-05-10 21:18 UTC
So I've tried to compile the latest commit ( 951a383 ) on Debian with GTK3, and everything went fine compile-wise, except when I try to run the emulator:

```
$ snes9x-gtk 

(snes9x-gtk:8486): GLib-GObject-WARNING **: The property GtkAlignment:top-padding is deprecated and shouldn't be used anymore. It will be removed in a future version.

(snes9x-gtk:8486): GLib-GObject-WARNING **: The property GtkImage:stock is deprecated and shouldn't be used anymore. It will be removed in a future version.

(snes9x-gtk:8486): GLib-GObject-WARNING **: The property GtkMisc:xpad is deprecated and shouldn't be used anymore. It will be removed in a future version.

(snes9x-gtk:8486): GLib-GObject-WARNING **: The property GtkMisc:ypad is deprecated and shouldn't be used anymore. It will be removed in a future version.

(snes9x-gtk:8486): GLib-GObject-WARNING **: The property GtkContainer:resize-mode is deprecated and shouldn't be used anymore. It will be removed in a future version.

(snes9x-gtk:8486): GLib-GObject-WARNING **: The property GtkButton:use-stock is deprecated and shouldn't be used anymore. It will be removed in a future version.

(snes9x-gtk:8486): GLib-GObject-WARNING **: The property GtkSettings:gtk-button-images is deprecated and shouldn't be used anymore. It will be removed in a future version.
Fontconfig error: "/home/andoru/.config/fontconfig/fonts.conf", line 38: junk after document element
Fontconfig error: "~/.fonts.conf", line 38: junk after document element

(snes9x-gtk:8486): GLib-GObject-WARNING **: The property GtkImageMenuItem:image is deprecated and shouldn't be used anymore. It will be removed in a future version.

(snes9x-gtk:8486): GLib-GObject-WARNING **: The property GtkSettings:gtk-menu-images is deprecated and shouldn't be used anymore. It will be removed in a future version.

(snes9x-gtk:8486): Gtk-CRITICAL **: gtk_widget_set_double_buffered: assertion 'GTK_IS_WIDGET (widget)' failed

(snes9x-gtk:8486): Gtk-CRITICAL **: gtk_widget_realize: assertion 'GTK_IS_WIDGET (widget)' failed

(snes9x-gtk:8486): GLib-GObject-WARNING **: invalid (NULL) pointer instance

(snes9x-gtk:8486): GLib-GObject-CRITICAL **: g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

(snes9x-gtk:8486): Gtk-CRITICAL **: gtk_widget_get_display: assertion 'GTK_IS_WIDGET (widget)' failed

(snes9x-gtk:8486): Gdk-CRITICAL **: gdk_x11_display_get_xdisplay: assertion 'GDK_IS_DISPLAY (display)' failed

(snes9x-gtk:8486): Gtk-CRITICAL **: gtk_widget_realize: assertion 'GTK_IS_WIDGET (widget)' failed

(snes9x-gtk:8486): Gtk-CRITICAL **: gtk_widget_get_display: assertion 'GTK_IS_WIDGET (widget)' failed

(snes9x-gtk:8486): Gdk-CRITICAL **: gdk_x11_display_get_xdisplay: assertion 'GDK_IS_DISPLAY (display)' failed

(snes9x-gtk:8486): Gtk-CRITICAL **: gtk_widget_get_screen: assertion 'GTK_IS_WIDGET (widget)' failed

(snes9x-gtk:8486): Gdk-CRITICAL **: gdk_screen_get_root_window: assertion 'GDK_IS_SCREEN (screen)' failed
Segmentation fault
```

Here's [config.log](http://s000.tinyupload.com/index.php?file_id=72446512803186253102)

I'm currently using Debian Sid

**Comment by andoruB** [comment] 2015-05-10 21:31
As with issue #75, it works flawlessly when compiling with GTK2

**Comment by BearOso** [comment] 2015-05-11 04:25
Aside from the deprecation warnings, recent gtk3 broke gtkdrawingarea among other things, which causes the crashes. I'll have to look into it, but it might not be a simple fix. Stick with gtk2 for now.

**Comment by andoruB** [comment] 2015-05-11 15:20
Will do :)  
Thanks for keeping the project alive!

**Comment by sergiobenrocha2** [comment] 2015-06-03 05:33
I'm getting the same problem on Debian 8.

I'll try to push it to debian non-free repo, it would be interesting if it's fixed.

**Comment by vgturtle127** [comment] 2015-09-27 05:49
Can we close this, and maybe add some stuff to the docs and Wiki about the GTK version?

**Comment by sergiobenrocha2** [comment] 2015-09-27 22:26
Close why? Gtk 2 will be deprecated in the next years, one day it should update fully to gtk 3

**Comment by vgturtle127** [comment] 2015-09-28 04:24
Yeah, but I think that an issue isn't really the best way to go about a change from GTK2 to GTK3. If GTK3 doesn't work at all at the moment, anyway. I don't know, I assumed that an issue just wasn't an appropriate way to handle a large code change. I will leave it up to you guys obviously, but we can at least merge some issues together.

**Comment by BearOso** [comment] 2015-09-29 19:31
Latest git code works with GTK+ 3, but with deprecation warnings. The problem is that GTK+ 3 isn't actually API-stable. It changes with each minor release at the whims of GNOME developers. Since we can't rely on GTK+ 3 keeping features through minor releases, it's best to stick to GTK+ 2 for now. I'm not planning on pushing forward to 3 anymore. QT5 might be the next step, but that would be a significant rewrite.

**Comment by vgturtle127** [comment] 2015-09-30 02:48
Alright. QT is way better anyway. :laughing: 

I thought that GTK was getting axed by many developers because it was thought that it would eventually be depreciated? Maybe I am wrong.

**Comment by andoruB** [comment] 2015-10-29 18:05
Can confirm that the GTK+3 build of the latest commit works.

**Comment by bearoso** [comment] 2018-10-24 21:44
GTK 3 works fine now, and is the preferred option.

**Closed by bearoso** 2018-10-24 21:44 UTC
Labels: build, gtk
