### ISSUE TITLE
MSU-1: Left and right stereo channels swap upon loop

### ISSUE THREAD

**Issue by vince94** [snes9xgit/snes9x#307] opened 2018-05-27 00:28 UTC
I thought I noticed something off, so I made this stereo test, and sure enough, [it seems to be swapping the left and right channels](https://youtu.be/6vza7jJqj04). The .pcm file is [here](https://www.dropbox.com/s/hfrxx2i1cdyt9ao/MSU-1%20stereo%20test.pcm?dl=0), if you'd like to test it out.
I am using Snes9X v1.55 for Windows

**Comment by bearoso** [comment] 2018-05-27 00:30
Interesting. Should be easy enough to fix. I’ve stayed away from the MSU1 for the most part and just let @qwertymodo do his magic, maybe he wants to fix this one?

**Comment by qwertymodo** [comment] 2018-05-27 01:06
Even weirder, if the loop point is set to sample 0, it's correct the first time, if it's set to anything else, it's swapped the first time.  I'll look into it.

**Comment by bearoso** [comment] 2018-05-27 01:36
If you have it offset by one anywhere that'll switch the channels on you.

**Comment by qwertymodo** [comment] 2018-05-27 01:37
I think I found the issue, testing it now.

**Comment by qwertymodo** [comment] 2018-05-27 01:39
Yeah, found it.  When it reached the end of the file, it was putting an empty sample into the buffer before seeking to the loop point, causing the channels to be offset by a single sample, which swapped them.  However, that doesn't explain the behavior I was seeing regarding the first loop, so I'm going to poke around a bit more before I commit it.

**Comment by qwertymodo** [comment] 2018-05-27 03:05
I've pushed a commit that should solve the issue, but I feel like a better solution would have been to ensure the APU always generates an even number of samples.

**Comment by qwertymodo** [comment] 2018-05-27 15:55
Well, then something is wrong. My change forces an even number of MSU-1 samples to be generated and for the buffer position to be aligned to even samples at every call of GenerateSamples, but that ignores the root cause because I'm still not super comfortable in the APU. Maybe I can just throw in a debug assert and backtrace from there.

**Comment by bearoso** [comment] 2018-05-27 16:10
Definitely try to find the root cause. I'd assert SNES::dsp.spc_dsp.sample_count() always returns a multiple of 2. 

Knowing me, I messed something up along the line.

**Comment by bearoso** [comment] 2018-05-27 16:14
Looking at the partial_samples logic makes me think it might actually be that. We should be using audio "frames" for that calculation instead.

**Comment by bearoso** [comment] 2018-05-27 16:30
I think renaming partial_samples to partial_frames and doing something like this in S9xMSU1Generate:
```
void S9xMSU1Generate(size_t sample_count)
{
	partial_frames += 4410 * (sample_count / 2);

	while (((uintptr_t)bufPos < (uintptr_t)bufEnd) && partial_frames > 3204)
	{
		if (MSU1.MSU1_STATUS & AudioPlaying && audioStream)
		{
			int16 sample_left;
			int16 sample_right;
			int bytes_read = READ_STREAM((char *)&sample_left,  2, audioStream);
			bytes_read    += READ_STREAM((char *)&sample_right, 2, audioStream);

			if (bytes_read == 4)
			{
				sample_left  = (int16)((double)(int16)GET_LE16(&sample_left)  * (double)MSU1.MSU1_VOLUME / 255.0);
				sample_right = (int16)((double)(int16)GET_LE16(&sample_right) * (double)MSU1.MSU1_VOLUME / 255.0);

				*(bufPos++) = sample_left;
				*(bufPos++) = sample_right;
				MSU1.MSU1_AUDIO_POS += 4;
				partial_frames -= 3204;
			}
			else
			if (bytes_read >= 0)
			{
				if (MSU1.MSU1_STATUS & AudioRepeating)
				{
					MSU1.MSU1_AUDIO_POS = audioLoopPos;
					REVERT_STREAM(audioStream, MSU1.MSU1_AUDIO_POS, 0);
				}
				else
				{
					MSU1.MSU1_STATUS &= ~(AudioPlaying | AudioRepeating);
					REVERT_STREAM(audioStream, 8, 0);
				}
			}
			else
			{
				MSU1.MSU1_STATUS &= ~(AudioPlaying | AudioRepeating);
			}
		}
		else
		{
			MSU1.MSU1_STATUS &= ~(AudioPlaying | AudioRepeating);
			partial_frames -= 3204;
			*(bufPos++) = 0;
		}
	}
}
```
Is better. We never add to the buffer unless we have all 4 bytes for left and right channels.

**Comment by bearoso** [comment] 2018-05-27 16:42
Something with the IRQ changes also broke your chrono trigger video.

**Comment by qwertymodo** [comment] 2018-05-27 16:53
Interesting, not sure why that would have happened, I'm not doing anything too crazy, just waiting for a particular scanline, enabling force blank, DMA, wait for scanline, disable force blank, over and over.

**Comment by bearoso** [comment] 2018-05-27 17:37
I figured it out. Just a corner case I missed.

**Comment by bearoso** [comment] 2018-06-03 00:31
I'm going to assume this is fixed, then.

**Comment by qwertymodo** [comment] 2018-06-03 00:55
Sorry I didn't get a chance to test before now.  Swapping on loop is fixed, but it's still getting swapped sometimes on initial load.

**Comment by bearoso** [comment] 2018-06-03 01:02
I got it. Fixed in df02ba62fd2a84ae53e8919cfb6e630defb33caf.

**Comment by qwertymodo** [comment] 2018-06-03 01:12
I'm getting some serious garbage noise that I think is happening during fade-out.  I'm not sure when it started, so I'm bisecting now.

**Comment by bearoso** [comment] 2018-06-03 01:15
Probably my integer thing with the volume.

**Comment by qwertymodo** [comment] 2018-06-03 01:29
Everything about that commit looks so wrong, but it does in fact seem to work.

**Comment by qwertymodo** [comment] 2018-06-03 01:31
The swapping does appear to be fixed as well, but I'm going to keep testing for awhile before I can say so definitively, the behavior was somewhat random.

**Comment by bearoso** [comment] 2018-06-03 01:39
The swapping problem I think was because before it was playing it was filling the buffer with samples, one by one instead of both left and right. The buffer must’ve been under flowing during this time and we didn’t notice.

**Comment by qwertymodo** [comment] 2018-06-03 01:40
We can probably remove the pointless alignment on the MSU landing buffer in apu.cpp now.

**Comment by bearoso** [comment] 2018-06-04 21:15
Done. I'll close this again.

**Closed by bearoso** 2018-06-04 21:15 UTC
