### ISSUE TITLE
Bug Chou Aniki black screen after first round

### ISSUE THREAD

**Issue by bladeoner** [snes9xgit/snes9x#452] opened 2018-11-20 12:46 UTC
The game is booting after the change #187 https://github.com/snes9xgit/snes9x/commit/099bd60db0bec16b62a9351c32b24d3909ea55f2 and you can play but after the first round you will get a black screen and still hear the sound of the game. After a while it continues to the second round.

supersonicjc confirmed that this regression is until snes9x 1.51.

I tried to increase the APU value but that didn't change anything, it's also not clear which coprocessor this game uses.

**Comment by bearoso** [comment] 2018-11-20 17:22
It's not a coprocessor screwing with it, it's just a poorly programmed hack. It relies on a value randomly coming into range to be picked up by an NMI, and it's a coincidence that it now works on hardware and bsnes. If you look closely, you'll see that now and then even on hardware/bsnes, it misses a frame when some text appears on top of the screen because it was waiting for vsync, but things didn't align properly for it to work.

**Comment by bladeoner** [comment] 2018-11-20 17:36
@bearoso Thank you for clarifying that, I will close the issue.

**Comment by bearoso** [comment] 2018-11-20 17:51
Scratch that, it was Kohryu no Mimi that had the bad hack.

**Comment by bearoso** [comment] 2018-11-20 21:37
It seems to want the CPU faster and the APU slower, so a timing hack of -3 works for now. The CPU is recording too many clock cycles doing something. Reducing the DMA sync delay to 0 isn't even enough, so it's not that.

**Comment by bearoso** [comment] 2018-11-23 22:37
Duplicate of #187.

**Closed by bearoso** 2018-11-23 22:37 UTC
