### ISSUE TITLE
Remove non-free clause

### ISSUE THREAD

**Issue by misterhat** [snes9xgit/snes9x#80] opened 2015-06-03 06:04 UTC
Is it feasible to remove the non-commercial clause and relicense snes9x under a free license (permissive or no)? I understand this is pretty difficiult due to all the people involved, but is it something that's been considered? Recently another emulation project, MAME, has done this for the following reasons:

> developer Miodrag Milanovic explained that the change is intended to draw more developer interest to the project, allow the manufacturers of games to distribute MAME to emulate their own games, and make the software a "learning tool for developers working on development boards".

It would really help with making snes9x easier to distribute as well, since snes9x is currently nonfree and therefore non-compliant with packaging standards in mainstream GNU/Linux distributions.

**Comment by sergiobenrocha2** [comment] 2015-06-03 06:06
Only one word: retron5

**Comment by OV2** [comment] 2015-06-03 14:30
That's not feasible - as you stated there are too many people involved, many of which have disappeared. It's also not something I'd want to do.

**Comment by vgturtle127** [comment] 2015-09-27 05:47
Can we close this if the issue is no longer needed?

**Comment by jcdenton2k** [comment] 2016-07-16 23:02
@sergiobenrocha2 said it best; I would rather the hard work of emulator authors and contributors not be ripped off for commercial profit (without contributing back to the community that created it) like Hyperkin, Microsoft, Nintendo, and Sony have done (along with many MANY other companies).

**Closed** 2018-10-24 21:43 UTC
Labels: meta
