### ISSUE TITLE
Super GameBoy Emulation

### ISSUE THREAD

**Issue by AlexN64gamer** [snes9xgit/snes9x#357] opened 2018-07-12 11:25 UTC
would it possible to add Super GameBoy emulation to the next release of this great emulator? I like it over higan cause Snes9x is way more fast without being to inaccurate, so I would really like to have Super GameBoy to play some games like DonkeyKong or Pokemon which had their specific palletes and borders, if I can help you in anyway, just ask me : )

**Comment by jjfmz42015** [comment] 2018-07-12 14:51
I dont know what is involved in that however that would be cool

**Comment by qwertymodo** [comment] 2018-07-12 16:22
That would require writing (or copying) an entire GameBoy emulator.  Not at all a trivial task.

**Comment by jjfmz42015** [comment] 2018-07-12 17:10
not worth it then considering how many gb emus exist and it would take people away from polishing the primary emulator

**Comment by magiblot** [comment] 2018-07-12 18:04
The actual Super Game Boy uses embedded Game Boy-like hardware to run games. It's not a software emulator. Thus, Super Game Boy emulation should be done in a Game Boy emulator (I have never found one which does, unfortunately).

**Comment by raekuul** [comment] 2018-07-12 18:06
If you just want the palettes and borders, several GB emulators - the one most readily coming to mind is bgb - will actually give you the option of using the SGB border/palette on game load.

If, like me, you actually want to emulate the SGB environment, that's a bit more complex. The most faithful way to recreate the environment right now is to use a fork of lsnes designed for this purpose. lsnes calls the sgb firmware, and then starts a thread for gambatte to handle the gb emulation. As you can imagine, while it's great for science, it's not the best environment to actually _play_ gb games in.

**Comment by qwertymodo** [comment] 2018-07-12 19:12
bsnes/higan supports Super GameBoy emulation.  I know it's on the resource-heavy side, but you're emulating 2 complete systems at once.  I believe byuu plans to (or already does) support it in the new bsnes release as well, which will be much more accessible resource-wise.

**Comment by AlexN64gamer** [comment] 2018-07-12 19:40
im not talking about a "game boy emulator" there are currently NO game boy emulators that can do Super Game Boy capabilities other than borders or palletes, the actual super gameboy cartridge had many other features like various different borders, pallete color customization and drawing features, anyway, thanks for saying that my suggestion is "pointless" without even trying...

**Comment by qwertymodo** [comment] 2018-07-12 19:46
You actually *are* talking about a GameBoy emulator, you just don't realize it.  The Super GameBoy is an entire GameBoy system inside an SNES cartridge, along with a few other features on the SNES side.  So, while you're right that you won't get the full experience within a standalone GB emulator, emulating the Super GameBoy *does* require fully emulating the GameBoy, in addition to the Super Nintendo emulation.  If you want the full Super GameBoy experience in an emulator, you can do exactly that with higan or bsnes (I know the pre-higan versions support it, I'm not sure if the new beta does yet).  I'm not saying your suggestion is pointless, I'm just saying it's a HUGE amount of work.

**Comment by bearoso** [comment] 2018-07-12 20:16
Yep, this is a no go. We'd need a complete, accurate gameboy emulator, and no existing emulator will be compatible with Snes9x's license, so we'd have to write our own. Not going to happen.

**Comment by AlexN64gamer** [comment] 2018-07-12 22:18
ok, try pokemon yellow rom on bsnes 0.73 and tell me what you get, please

**Comment by AlexN64gamer** [comment] 2018-07-12 22:35
ok, no problem I just tested it with 106r44, try pokemon yellow special pikachu edition rom (usa,europe) with that bsnes version and see it by yourselves

**Comment by bearoso** [comment] 2018-07-12 22:50
See what? It works fine there, and it should. bsnes 0.73 included a separate gameboy emulator called "gambatte" to handle the extra hardware and later versions use a different gameboy emulator byuu wrote.

**Comment by AlexN64gamer** [comment] 2018-07-12 22:52
doesnt work fine, it should load a green border with pikachu around it and use special color pallete, it just loads it as any normal game boy game

**Comment by bearoso** [comment] 2018-07-12 23:14
I think that's probably related to it being both a gameboy color game and super gameboy game in one. With the emulator supporting both it's confused. You'll need to send that bug report to byuu.

**Comment by qwertymodo** [comment] 2018-07-15 23:10
Turns out higan/bsnes had a bug with proper SGB detection, but it's fixed now.  I'm going to go ahead and close this ticket as a wontfix, but I can confirm that bsnes works with both the SGB1 and SGB2 ROMs.  For anybody who can't get it working, you need 3 things to get it working in the latest bsnes v106 WIP.

-sgb1.boot.rom or sgb2.boot.rom, should be included with the bsnes download.  Should be 256 bytes, named exactly as shown here, and located in the bsnes/firmware folder
-Super Game Boy (World).sfc or Super Game Boy 2 (Japan).sfc program ROM.  Should be 256Kbytes.  Location doesn't matter.
-Your Game Boy game ROM

Open bsnes.  System>Load Game>Select your .sfc ROM.  A second file select dialog should open.  Now select your Game Boy ROM.

**Closed by qwertymodo** 2018-07-15 23:10 UTC

**Comment by aus101** [comment] 2025-04-08 11:05
> im not talking about a "game boy emulator" there are currently NO game boy emulators that can do Super Game Boy capabilities other than borders or palletes, the actual super gameboy cartridge had many other features like various different borders, pallete color customization and drawing features, anyway, thanks for saying that my suggestion is "pointless" without even trying...

@AlexN64gamer @qwertymodo 

Mesen is way easier to use than higan/bsnes and I can't imagine is as demanding.

![Image](https://github.com/user-attachments/assets/1acbcace-b2c4-43f8-9f46-3a4261453f12)
