### ISSUE TITLE
Sound is not working on Debian 9

### ISSUE THREAD

**Issue by avique-ufmg** [snes9xgit/snes9x#501] opened 2019-02-20 18:29 UTC
I downloaded the whole master source code, a couple of hours ago. I took a few minutes and tries to discover the things to pass to configure script, and I ended with this line:

`$ ./configure --prefix="/algum/lugar/.raiz/" --enable-zip --enable-gzip --enable-screenshot --enable-xvideo --enable-xinerama --enable-sound`

Now I can run the compiled snes9x with this line, but there is no sound:

` ./snes9x rom.sfc`

The output of that command starts with:

`

Snes9x 1.58 for unix
ERROR: Failed to open sound device /dev/dsp for writing.
	(Try loading snd-pcm-oss module?)
Port 1: Pad \#1. Port 2: <none>. 
No ROM file header found.
Map_LoROMMap
"TETRIS ATTACK" [checksum ok] LoROM, 8Mbits, ROM, NTSC, SRAM:0Kbits, ID:AYLE, CRC32:6C128210
joystick: No joystick found.
`

Note: I have seen a comment about version 1.59. Did I download the wrong version? What is the place to download the newest release (not beta or alpha, please!).

**Comment by avique-ufmg** [comment] 2019-02-20 18:30
How should I escape the "#1" inside the snes9x output so it is not transformed in a link?

**Comment by bearoso** [comment] 2019-02-20 18:48
That’s the barebones Unix version. If you want more features, you have to use the GTK version. You’re not getting sound because you don’t have the oss module loaded and/or pulse audio is overriding it. You can use the ALSA driver instead, or use the GTK version that has even more drivers.

**Comment by bearoso** [comment] 2019-02-20 18:48
That’s the barebones Unix version. If you want more features, you have to use the GTK version. You’re not getting sound because you don’t have the oss module loaded and/or pulse audio is overriding it. You can use the ALSA driver instead, or use the GTK version that has even more drivers.

**Comment by bearoso** [comment] 2019-02-20 18:48
That’s the barebones Unix version. If you want more features, you have to use the GTK version. You’re not getting sound because you don’t have the oss module loaded and/or pulse audio is overriding it. You can use the ALSA driver instead, or use the GTK version that has even more drivers.

**Comment by bearoso** [comment] 2019-02-20 18:49
That’s the barebones Unix version. If you want more features, you have to use the GTK version. You’re not getting sound because you don’t have the oss module loaded and/or pulse audio is overriding it. You can use the ALSA driver instead, or use the GTK version that has even more drivers.

**Comment by bearoso** [comment] 2019-02-20 18:49
That’s the barebones Unix version. If you want more features, you have to use the GTK version. You’re not getting sound because you don’t have the oss module loaded and/or pulse audio is overriding it. You can use the ALSA driver instead, or use the GTK version that has even more drivers.

**Comment by bearoso** [comment] 2019-02-21 01:53
Either as root or with sudo, execute:
`modprobe snd-pcm-oss`

or run snes9x by using
`padsp snes9x`
with whatever options you want. 

> I have the GTK version installed, but it is not compiled with the command line switches I want to use.

What command line switches are those, exactly?

**Comment by bearoso** [comment] 2019-02-22 04:05
snd-pcm-oss is the ALSA compatibility module for OSS, the sound protocol the Unix version uses. It should create the /dev/dsp device nodes necessary for sound. The nodes in the snd directory are for ALSA only.

**Comment by bearoso** [comment] 2019-02-28 20:36
Not a bug. You’re free to continue posting if you need more help, but I’m closing the issue.

**Closed by bearoso** 2019-02-28 20:36 UTC
