### ISSUE TITLE
Tales of Phantasia and Star Ocean

### ISSUE THREAD

**Issue by noooq** [snes9xgit/snes9x#392] opened 2018-08-15 02:24 UTC
Testing git e321ec. Tales of Phantasia has no sound and stalls after the first screen. Star Ocean, similar, no sound and eventually stalls after some logos.

**Comment by OV2** [comment] 2018-08-15 11:31
I can't reproduce that. Are you using the GTK version? 0b75e2de9dee80cdb74bf739e6e7d728ca569fe1 might be related, you'd get that effect with overclocking enabled.

**Comment by Tatsuya79** [comment] 2018-08-15 12:10
No problem here too.
And yes, the overclock setting would do that with these games.

**Comment by jjfmz42015** [comment] 2018-08-15 12:31
also tested win x64 e3216ec8 no issue.

**Comment by bearoso** [comment] 2018-08-15 15:30
Likewise, no problem here. It's easy to forget you have those overclocking things enabled. In the GTK+ version I made sure to label them harshly so you'd know what you're doing. 

Sometimes when I go back to older versions to bisect things will break and I'll think "what did I screw up now." And it turns out it loaded the cheat file as garbage.

**Comment by noooq** [comment] 2018-08-15 23:52
This is on the libretro running on retroarch. I'm fairly certain all the special overclock options were set to off. I tried again with git 2606694 and I don't see it happen in that version so it seems resolved.

**Comment by Tatsuya79** [comment] 2018-08-17 13:33
@noooq Good to hear, you can close this issue then.

**Closed** 2018-08-17 15:17 UTC
