### ISSUE TITLE
Switching to OpenGL Crash / pervious version are working

### ISSUE THREAD

**Issue by JonKaruzu** [snes9xgit/snes9x#313] opened 2018-05-28 14:33 UTC
I recently compiled today (Snes9x Git 2018-05-28).
It fixed today but there is any issue.

I extracted the zip, Open the Emulator, working fine, Video > Display Configuration > Switch to OpenGL and Boom!
https://cdn.discordapp.com/attachments/381187250265784320/450666113219428352/Capture-537.png
It crashed.

My spec
CPU: Intel Celeron M 1.60Ghz 1 core
RAM: 508MB
OS: Windows XP SP3
GPU: Mobile Intel 945GM Express Chipset Family

I always use for Arcarde Boards or whatever

**Comment by bearoso** [comment] 2018-05-28 18:15
@OV2: It's an old intel graphics chip like you mentioned before. It's probably calling an extension function whose pointer is null because there's no support.

**Comment by OV2** [comment] 2018-05-28 18:37
Hm, I thought all the "advanced" functions were only used in the shader code... I'll see if I still have an old system around here somewhere.

**Comment by jjfmz42015** [comment] 2018-05-28 18:54
I suggest he also makes sure he is using intels latest driver for his chipset. makes sense no?

**Comment by bearoso** [comment] 2018-05-28 18:54
Yeah, I'm looking it over and can't find anything used unsafely. The 945GM is supposedly OpenGL 1.4 at max.

**Comment by bearoso** [comment] 2018-05-28 19:48
The only thing I could find is that GL_MAJOR_VERSION isn't a valid enum until 3.0.

**Comment by bearoso** [comment] 2018-05-29 19:12
@OV2: Did you manage to narrow this down yet?

**Comment by OV2** [comment] 2018-05-29 20:29
I have one system with an IGM 3150, where the problem is that the loader generator uses (and requires) glGetStringi to load extension functions, and without it will not load any functions at all. I'll try to fiddle with it or find an alternative.

**Comment by bearoso** [comment] 2018-05-29 21:07
That should be pretty easy to work around. glGetStringi is 3.0 only, so we need to check the version and use the usual glGetStringv with lower.

**Comment by bearoso** [comment] 2018-05-29 21:14
I pushed something. Let's see if it works.

**Comment by bearoso** [comment] 2018-05-29 21:22
After a quick fix, it works fine on my higher GL version.

**Comment by OV2** [comment] 2018-05-29 21:42
I wanted to check if the generator has an option for loading compatibility or something similar, but it does not look like it.

Your change works on the IGM system (at least it does not crash - no monitor connected and rdp doesn't like opengl), maybe the op can give some feedback if it also works for him.

**Comment by bearoso** [comment] 2018-05-29 21:45
> I wanted to check if the generator has an option for loading compatibility or something similar, but it does not look like it.

Ha ha. That's actually what I did. I ran the generator for 1.4 and copied over the loading functions, using them based on version. I changed the version check to always use the string version, though, because I don't think that's deprecated yet.

**Comment by bearoso** [comment] 2018-06-03 00:39
I'm going to go ahead and close this. @JonKaruzu, let us know if this isn't fixed and reopen it.

**Closed by bearoso** 2018-06-03 00:39 UTC

**Comment by JonKaruzu** [comment] 2018-06-03 00:53
Oh, I worked. Thanks
