### ISSUE TITLE
Fullscreen borders flickering when using Direct 3D

### ISSUE THREAD

**Issue by semecan** [snes9xgit/snes9x#531] opened 2019-04-25 16:18 UTC
As the title says the black borders in fullscreen mode flicker when I select Direct 3D as the rendering engine. 
Snes9x version: 1.60 Win32/x64
Platform: Windows 7

**Comment by OV2** [comment] 2019-04-25 17:30
This doesn't happen for me - can you post your snes9x.conf file?

**Comment by semecan** [comment] 2019-04-25 17:36
Here it is. Had to zip it cause github does not support .conf files.
[conf.zip](https://github.com/snes9xgit/snes9x/files/3118158/conf.zip)

**Comment by semecan** [comment] 2019-04-25 17:40
I also just tested version 1.59.2 again using the snes9x.conf I posted. With that version there is no flickering for me.

**Comment by OV2** [comment] 2019-04-25 18:50
I don't see any changes that could cause this, and have so far been unable to reproduce it on two different systems. Maybe I can find a windows 7 system at work.

**Comment by bearoso** [comment] 2019-04-25 19:15
I think it's because the fullscreen flags changed in the "true fullscreen" mode. One of the buffers probably isn't being cleared properly, so it's flickering between garbage and black. This could be fixed by doing Clear, Present, Clear instead of just Clear. But we should probably just clear before every frame.

**Comment by semecan** [comment] 2019-04-25 19:15
The issue seems to be related to the color depth in the Fullscreen Display Settings. 
If i Select 1920 x 1080 x 32bit 144hz, it flickers. If I change to 1920 x 1080 x 16bit 144hz, the flickering stop.

**Comment by bearoso** [comment] 2019-04-25 19:17
@semecan, I think that's just random, whether or not the GPU memory has zeroes or garbage in it at the time of creation. It's just lack of initialization.

**Comment by semecan** [comment] 2019-04-25 19:21
@bearoso that could be true too, I have no knowledge of all of that works. But another observation I just made is that when enabling Windows Aero, the flickering stops on 32 bits. As soon as I switch back to the classic theme, it goes back to flickering.

**Comment by OV2** [comment] 2019-04-25 19:26
Try disabling the "enable triple buffering" checkbox - if it's the issue bearoso mentioned that should affect it.

**Comment by semecan** [comment] 2019-04-25 19:33
@OV2 sadly, changing that option does not affect the flickering.

**Comment by semecan** [comment] 2019-04-26 15:54
I have not been able to reproduce the problem on a second system, so I assume it is tied to specific graphics cards, making it a very niche cache propably not worth investing too much effort in fixing.
I will just use the emulated fullscreen mode which already removes all flickering for me.

**Comment by themalu866** [comment] 2019-04-28 15:23
I tested on Windows 7 and what happens:
- on DirectDraw and Direct3D after going fullscreen (not the emulated) the screen flicks black just a little but only if Reduce Input Lag is ON.
- on OpenGL the screen doesn't flick but there's a screen tearing to it on both fullscreens options (emulated or not) and it happens even if VSync is on.
- games are never pixel perfect on both fullscreens options, it's very noticeable on A Link to the Past and Chrono Trigger because the characters eyes keep changing sizes depending on where they are on the screen.

**Comment by Nicholas-Steel** [comment] 2019-05-20 16:47
I don't observe flickering but when using Direct3D Fullscreen anything that appears in the black space on either side of the 4:3 game will not clear up/black bars will retain the last displayed image in that space.

Noticeable when seeing notifications from Geforce Experience for example.

**Comment by bearoso** [comment] 2019-05-20 16:53
It's totally related. We just need to clear that area every frame.

**Comment by OV2** [comment] 2019-05-20 17:34
We're already calling clear each frame. Maybe the viewport needs to be reset before clearing.

**Comment by OV2** [comment] 2019-06-14 09:55
I've reproduced this at work, and the committed change fixed it.

**Closed by OV2** 2019-06-14 09:55 UTC
