### ISSUE TITLE
1.62.1 no music with msu-1 hacks and freezes on  videos 

### ISSUE THREAD

**Issue by p3st-textures** [snes9xgit/snes9x#836] opened 2023-03-27 00:21 UTC
i just wanted to notice a thing ^^

like the title said i get no music or sounds anymore form the msu-1 stuff ,
tryied a few games... nothing 
also  my alttp uses the intro video patch , at the video snes9x  freezes now
super roadblaster doesn´t even  start .

with the last version everything works fine

**Comment by OV2** [comment] 2023-03-27 00:49
What style of msu are you trying to open, and what platform are you using?

I tried an uncompressed msu (sfc, bps and msu/pcm files in the same folder, chrono trigger) as well as a .msu1 pack (super road blaster) - both worked fine.

**Comment by p3st-textures** [comment] 2023-03-27 22:19
i have only uncompressed msu games ...and thats strange  for me the games work but not the music , and as i said video freezes

i use the core version  over retroarch on win 10 64bit ...with the gl video driver btw

**Comment by OV2** [comment] 2023-03-29 12:10
This should be fixed, can you try the latest auto-generated build?

**Comment by p3st-textures** [comment] 2023-03-30 01:51
autogeratet build where can i get that ? do you mean over libreto build bot and then nighlty or what ^^ 
i am not very familiar rwith git/github otherwise sry

**Closed** 2023-03-30 09:04 UTC

**Comment by ds22x** [comment] 2023-05-08 22:06
https://github.com/snes9xgit/snes9x/commit/33d84d31b8b86e10a3d0638d1282ce2f0063d414#diff-08fd608692cc3277cc9ae722ea56caf18db9987aa039e62485c91d8258185008R1129 seems to be causing issues when trying to connect through netplay on RetroArch.

**Comment by OV2** [comment] 2023-05-09 09:23
Can you describe this in more detail? It worked fine when I tried it with two instances on my system, connecting to one from the other.

**Comment by ds22x** [comment] 2023-05-09 12:13
The problem is that, when passing the game path, it expects it to be exactly at that path, hence why it works with two instances on the same system, but not when trying to connect two separate systems (I.E. two Windows setups where the rom is located at different paths etc.).

**Comment by ds22x** [comment] 2023-05-09 20:59
Found the solution.
https://github.com/snes9xgit/snes9x/pull/848

**Comment by OV2** [comment] 2023-05-09 21:04
The problem is not the loading of the rom, since LoadROMMem always loads from memory. The path is simply passed to the core so that S9xGetFilename can later be used to retrieve the rom path for possible other files (msu1 etc.).

Retroarch throws "Netplay state load with an unexpected save state size.". The problem is that the ROMFilename is part of the save state, which is why different names get different state sizes.

@bearoso: with the new S9xGetFilename in fscompat the port can no longer override this function, which is problematic if we want the ROMFilename to be a fixed string and still make msu1 etc. work. Should we add a define for this? Any better ideas?

**Comment by ds22x** [comment] 2023-05-09 21:25
So I assume using `g_basename` instead of `game->path` is not a good solution?

**Comment by OV2** [comment] 2023-05-09 21:44
This would work for cases where the rom filename is the same for all netplay parties. But if one party has the rom named `super_mario.sfc`, and the second party has named it `mario.sfc` you'd run into the same issue again.

**Comment by ds22x** [comment] 2023-05-09 22:09
Tried a 1.61 core, and it also refuses to connect when the roms don't share the same name.
Also tried the same setup with a completely different core setup (PicoDrive in this case) to check if only Snes9x refuses the connection with differently named roms, but the same thing occurred.

**Comment by bearoso** [comment] 2023-05-09 22:49
@bearoso: with the new S9xGetFilename in fscompat the port can no longer override this function, which is problematic if we want the ROMFilename to be a fixed string and still make msu1 etc. work. Should we add a define for this? Any better ideas?

An #ifdef around S9xGetFilename is fine if they need to have a special copy.

**Comment by OV2** [comment] 2023-05-10 10:39
> Tried a 1.61 core, and it also refuses to connect when the roms don't share the same name. Also tried the same setup with a completely different and unrelated core setup (PicoDrive in this case) to check if only Snes9x refuses the connection with differently named roms, but the same thing occurred.

I just tried this with 1.61 and it worked without problems. Maybe you ran into the issue that retroarch seems to autoupdate cores when starting netplay?

I'll try to do a fix that allows it again.

**Comment by ds22x** [comment] 2023-05-10 11:16
I did run into that initially, but I made sure to lock the cores from being auto-updated after that, so that's not the problem.

**Comment by bearoso** [comment] 2023-05-10 19:19
I just set it to the word "Removed" It'll always be the same size now, so we shouldn't have that problem.

**Comment by OV2** [comment] 2023-05-12 10:27
Finally got around to try it again, works fine now for different rom paths and rom names.
